// Country name translations keyed by slug, per language.
// Used to display localized country names instead of English defaults.

import type { Lang } from './i18n';

export const COUNTRY_NAMES: Record<string, Record<string, string>> = {
  "pt-br": {
    "united-states": "Estados Unidos",
    "india": "Índia",
    "united-kingdom": "Reino Unido",
    "china": "China",
    "germany": "Alemanha",
    "france": "França",
    "japao": "Japão",
    "remoto-global": "Remoto Global",
    "singapura": "Singapura",
    "sweden": "Suécia",
    "coreia-do-sul": "Coreia do Sul",
    "spain": "Espanha",
    "netherlands": "Países Baixos",
    "poland": "Polônia",
    "ireland": "Irlanda",
    "finland": "Finlândia",
    "portugal": "Portugal",
    "switzerland": "Suíça",
    "italy": "Itália",
    "denmark": "Dinamarca",
    "norway": "Noruega",
    "hong-kong": "Hong Kong",
    "belgium": "Bélgica",
    "taiwan": "Taiwan",
    "indonesia": "Indonésia",
    "tailandia": "Tailândia",
    "malasia": "Malásia",
    "austria": "Áustria",
    "vietna": "Vietnã",
    "filipinas": "Filipinas",
    "estonia": "Estônia",
    "czech-republic": "República Tcheca",
    "romania": "Romênia",
    "hungary": "Hungria",
    "luxembourg": "Luxemburgo",
    "ukraine": "Ucrânia",
    "greece": "Grécia",
    "paquistao": "Paquistão",
    "lithuania": "Lituânia",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bulgária",
    "cyprus": "Chipre",
    "croatia": "Croácia",
    "serbia": "Sérvia",
    "slovakia": "Eslováquia",
    "malta": "Malta",
    "iceland": "Islândia",
    "slovenia": "Eslovênia",
    "bangladesh": "Bangladesh",
    "latvia": "Letônia",
    "nepal": "Nepal",
    "moldova": "Moldávia",
    "georgia": "Geórgia",
    "albania": "Albânia",
    "north-macedonia": "Macedônia do Norte",
    "bosnia-and-herzegovina": "Bósnia e Herzegovina",
    "montenegro": "Montenegro",
  },
  "pt-pt": {
    "united-states": "Estados Unidos",
    "india": "Índia",
    "united-kingdom": "Reino Unido",
    "china": "China",
    "germany": "Alemanha",
    "france": "França",
    "japao": "Japão",
    "remoto-global": "Remoto Global",
    "singapura": "Singapura",
    "sweden": "Suécia",
    "coreia-do-sul": "Coreia do Sul",
    "spain": "Espanha",
    "netherlands": "Países Baixos",
    "poland": "Polónia",
    "ireland": "Irlanda",
    "finland": "Finlândia",
    "portugal": "Portugal",
    "switzerland": "Suíça",
    "italy": "Itália",
    "denmark": "Dinamarca",
    "norway": "Noruega",
    "hong-kong": "Hong Kong",
    "belgium": "Bélgica",
    "taiwan": "Taiwan",
    "indonesia": "Indonésia",
    "tailandia": "Tailândia",
    "malasia": "Malásia",
    "austria": "Áustria",
    "vietna": "Vietnã",
    "filipinas": "Filipinas",
    "estonia": "Estónia",
    "czech-republic": "República Checa",
    "romania": "Roménia",
    "hungary": "Hungria",
    "luxembourg": "Luxemburgo",
    "ukraine": "Ucrânia",
    "greece": "Grécia",
    "paquistao": "Paquistão",
    "lithuania": "Lituânia",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bulgária",
    "cyprus": "Chipre",
    "croatia": "Croácia",
    "serbia": "Sérvia",
    "slovakia": "Eslováquia",
    "malta": "Malta",
    "iceland": "Islândia",
    "slovenia": "Eslovénia",
    "bangladesh": "Bangladesh",
    "latvia": "Letónia",
    "nepal": "Nepal",
    "moldova": "Moldávia",
    "georgia": "Geórgia",
    "albania": "Albânia",
    "north-macedonia": "Macedónia do Norte",
    "bosnia-and-herzegovina": "Bósnia e Herzegovina",
    "montenegro": "Montenegro",
  },
  es: {
    "united-states": "Estados Unidos",
    "india": "India",
    "united-kingdom": "Reino Unido",
    "china": "China",
    "germany": "Alemania",
    "france": "Francia",
    "japao": "Japón",
    "remoto-global": "Remoto Global",
    "singapura": "Singapur",
    "sweden": "Suecia",
    "coreia-do-sul": "Corea del Sur",
    "spain": "España",
    "netherlands": "Países Bajos",
    "poland": "Polonia",
    "ireland": "Irlanda",
    "finland": "Finlandia",
    "portugal": "Portugal",
    "switzerland": "Suiza",
    "italy": "Italia",
    "denmark": "Dinamarca",
    "norway": "Noruega",
    "hong-kong": "Hong Kong",
    "belgium": "Bélgica",
    "taiwan": "Taiwán",
    "indonesia": "Indonesia",
    "tailandia": "Tailandia",
    "malasia": "Malasia",
    "austria": "Austria",
    "vietna": "Vietnam",
    "filipinas": "Filipinas",
    "estonia": "Estonia",
    "czech-republic": "República Checa",
    "romania": "Rumanía",
    "hungary": "Hungría",
    "luxembourg": "Luxemburgo",
    "ukraine": "Ucrania",
    "greece": "Grecia",
    "paquistao": "Pakistán",
    "lithuania": "Lituania",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bulgaria",
    "cyprus": "Chipre",
    "croatia": "Croacia",
    "serbia": "Serbia",
    "slovakia": "Eslovaquia",
    "malta": "Malta",
    "iceland": "Islandia",
    "slovenia": "Eslovenia",
    "bangladesh": "Bangladés",
    "latvia": "Letonia",
    "nepal": "Nepal",
    "moldova": "Moldavia",
    "georgia": "Georgia",
    "albania": "Albania",
    "north-macedonia": "Macedonia del Norte",
    "bosnia-and-herzegovina": "Bosnia y Herzegovina",
    "montenegro": "Montenegro",
  },
  fr: {
    "united-states": "États-Unis",
    "india": "Inde",
    "united-kingdom": "Royaume-Uni",
    "china": "Chine",
    "germany": "Allemagne",
    "france": "France",
    "japao": "Japon",
    "remoto-global": "Télétravail",
    "singapura": "Singapour",
    "sweden": "Suède",
    "coreia-do-sul": "Corée du Sud",
    "spain": "Espagne",
    "netherlands": "Pays-Bas",
    "poland": "Pologne",
    "ireland": "Irlande",
    "finland": "Finlande",
    "portugal": "Portugal",
    "switzerland": "Suisse",
    "italy": "Italie",
    "denmark": "Danemark",
    "norway": "Norvège",
    "hong-kong": "Hong Kong",
    "belgium": "Belgique",
    "taiwan": "Taïwan",
    "indonesia": "Indonésie",
    "tailandia": "Thaïlande",
    "malasia": "Malaisie",
    "austria": "Autriche",
    "vietna": "Viêt Nam",
    "filipinas": "Philippines",
    "estonia": "Estonie",
    "czech-republic": "République Tchèque",
    "romania": "Roumanie",
    "hungary": "Hongrie",
    "luxembourg": "Luxembourg",
    "ukraine": "Ukraine",
    "greece": "Grèce",
    "paquistao": "Pakistan",
    "lithuania": "Lituanie",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bulgarie",
    "cyprus": "Chypre",
    "croatia": "Croatie",
    "serbia": "Serbie",
    "slovakia": "Slovaquie",
    "malta": "Malte",
    "iceland": "Islande",
    "slovenia": "Slovénie",
    "bangladesh": "Bangladesh",
    "latvia": "Lettonie",
    "nepal": "Népal",
    "moldova": "Moldavie",
    "georgia": "Géorgie",
    "albania": "Albanie",
    "north-macedonia": "Macédoine du Nord",
    "bosnia-and-herzegovina": "Bosnie-Herzégovine",
    "montenegro": "Monténégro",
  },
  de: {
    "united-states": "USA",
    "india": "Indien",
    "united-kingdom": "Vereinigtes Königreich",
    "china": "China",
    "germany": "Deutschland",
    "france": "Frankreich",
    "japao": "Japan",
    "remoto-global": "Remote",
    "singapura": "Singapur",
    "sweden": "Schweden",
    "coreia-do-sul": "Südkorea",
    "spain": "Spanien",
    "netherlands": "Niederlande",
    "poland": "Polen",
    "ireland": "Irland",
    "finland": "Finnland",
    "portugal": "Portugal",
    "switzerland": "Schweiz",
    "italy": "Italien",
    "denmark": "Dänemark",
    "norway": "Norwegen",
    "hong-kong": "Hongkong",
    "belgium": "Belgien",
    "taiwan": "Taiwan",
    "indonesia": "Indonesien",
    "tailandia": "Thailand",
    "malasia": "Malaysia",
    "austria": "Österreich",
    "vietna": "Vietnam",
    "filipinas": "Philippinen",
    "estonia": "Estland",
    "czech-republic": "Tschechien",
    "romania": "Rumänien",
    "hungary": "Ungarn",
    "luxembourg": "Luxemburg",
    "ukraine": "Ukraine",
    "greece": "Griechenland",
    "paquistao": "Pakistan",
    "lithuania": "Litauen",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bulgarien",
    "cyprus": "Zypern",
    "croatia": "Kroatien",
    "serbia": "Serbien",
    "slovakia": "Slowakei",
    "malta": "Malta",
    "iceland": "Island",
    "slovenia": "Slowenien",
    "bangladesh": "Bangladesch",
    "latvia": "Lettland",
    "nepal": "Nepal",
    "moldova": "Moldau",
    "georgia": "Georgien",
    "albania": "Albanien",
    "north-macedonia": "Nordmazedonien",
    "bosnia-and-herzegovina": "Bosnien und Herzegowina",
    "montenegro": "Montenegro",
  },
  it: {
    "united-states": "Stati Uniti",
    "india": "India",
    "united-kingdom": "Regno Unito",
    "china": "Cina",
    "germany": "Germania",
    "france": "Francia",
    "japao": "Giappone",
    "remoto-global": "Remoto",
    "singapura": "Singapore",
    "sweden": "Svezia",
    "coreia-do-sul": "Corea del Sud",
    "spain": "Spagna",
    "netherlands": "Paesi Bassi",
    "poland": "Polonia",
    "ireland": "Irlanda",
    "finland": "Finlandia",
    "portugal": "Portogallo",
    "switzerland": "Svizzera",
    "italy": "Italia",
    "denmark": "Danimarca",
    "norway": "Norvegia",
    "hong-kong": "Hong Kong",
    "belgium": "Belgio",
    "taiwan": "Taiwan",
    "indonesia": "Indonesia",
    "tailandia": "Thailandia",
    "malasia": "Malesia",
    "austria": "Austria",
    "vietna": "Vietnam",
    "filipinas": "Filippine",
    "estonia": "Estonia",
    "czech-republic": "Repubblica Ceca",
    "romania": "Romania",
    "hungary": "Ungheria",
    "luxembourg": "Lussemburgo",
    "ukraine": "Ucraina",
    "greece": "Grecia",
    "paquistao": "Pakistan",
    "lithuania": "Lituania",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bulgaria",
    "cyprus": "Cipro",
    "croatia": "Croazia",
    "serbia": "Serbia",
    "slovakia": "Slovacchia",
    "malta": "Malta",
    "iceland": "Islanda",
    "slovenia": "Slovenia",
    "bangladesh": "Bangladesh",
    "latvia": "Lettonia",
    "nepal": "Nepal",
    "moldova": "Moldavia",
    "georgia": "Georgia",
    "albania": "Albania",
    "north-macedonia": "Macedonia del Nord",
    "bosnia-and-herzegovina": "Bosnia Erzegovina",
    "montenegro": "Montenegro",
  },
  nl: {
    "united-states": "Verenigde Staten",
    "india": "India",
    "united-kingdom": "Verenigd Koninkrijk",
    "china": "China",
    "germany": "Duitsland",
    "france": "Frankrijk",
    "japao": "Japan",
    "remoto-global": "Remote",
    "singapura": "Singapore",
    "sweden": "Zweden",
    "coreia-do-sul": "Zuid-Korea",
    "spain": "Spanje",
    "netherlands": "Nederland",
    "poland": "Polen",
    "ireland": "Ierland",
    "finland": "Finland",
    "portugal": "Portugal",
    "switzerland": "Zwitserland",
    "italy": "Italië",
    "denmark": "Denemarken",
    "norway": "Noorwegen",
    "hong-kong": "Hong Kong",
    "belgium": "België",
    "taiwan": "Taiwan",
    "indonesia": "Indonesië",
    "tailandia": "Thailand",
    "malasia": "Maleisië",
    "austria": "Oostenrijk",
    "vietna": "Vietnam",
    "filipinas": "Filipijnen",
    "estonia": "Estland",
    "czech-republic": "Tsjechië",
    "romania": "Roemenië",
    "hungary": "Hongarije",
    "luxembourg": "Luxemburg",
    "ukraine": "Oekraïne",
    "greece": "Griekenland",
    "paquistao": "Pakistan",
    "lithuania": "Litouwen",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bulgarije",
    "cyprus": "Cyprus",
    "croatia": "Kroatië",
    "serbia": "Servië",
    "slovakia": "Slowakije",
    "malta": "Malta",
    "iceland": "IJsland",
    "slovenia": "Slovenië",
    "bangladesh": "Bangladesh",
    "latvia": "Letland",
    "nepal": "Nepal",
    "moldova": "Moldavië",
    "georgia": "Georgië",
    "albania": "Albanië",
    "north-macedonia": "Noord-Macedonië",
    "bosnia-and-herzegovina": "Bosnië en Herzegovina",
    "montenegro": "Montenegro",
  },
  pl: {
    "united-states": "Stany Zjednoczone",
    "india": "Indie",
    "united-kingdom": "Wielka Brytania",
    "china": "Chiny",
    "germany": "Niemcy",
    "france": "Francja",
    "japao": "Japonia",
    "remoto-global": "Zdalnie",
    "singapura": "Singapur",
    "sweden": "Szwecja",
    "coreia-do-sul": "Korea Południowa",
    "spain": "Hiszpania",
    "netherlands": "Holandia",
    "poland": "Polska",
    "ireland": "Irlandia",
    "finland": "Finlandia",
    "portugal": "Portugalia",
    "switzerland": "Szwajcaria",
    "italy": "Włochy",
    "denmark": "Dania",
    "norway": "Norwegia",
    "hong-kong": "Hongkong",
    "belgium": "Belgia",
    "taiwan": "Tajwan",
    "indonesia": "Indonezja",
    "tailandia": "Tajlandia",
    "malasia": "Malezja",
    "austria": "Austria",
    "vietna": "Wietnam",
    "filipinas": "Filipiny",
    "estonia": "Estonia",
    "czech-republic": "Czechy",
    "romania": "Rumunia",
    "hungary": "Węgry",
    "luxembourg": "Luksemburg",
    "ukraine": "Ukraina",
    "greece": "Grecja",
    "paquistao": "Pakistan",
    "lithuania": "Litwa",
    "sri-lanka": "Sri Lanka",
    "bulgaria": "Bułgaria",
    "cyprus": "Cypr",
    "croatia": "Chorwacja",
    "serbia": "Serbia",
    "slovakia": "Słowacja",
    "malta": "Malta",
    "iceland": "Islandia",
    "slovenia": "Słowenia",
    "bangladesh": "Bangladesz",
    "latvia": "Łotwa",
    "nepal": "Nepal",
    "moldova": "Mołdawia",
    "georgia": "Gruzja",
    "albania": "Albania",
    "north-macedonia": "Macedonia Północna",
    "bosnia-and-herzegovina": "Bośnia i Hercegowina",
    "montenegro": "Czarnogóra",
  },
  ru: {
    "united-states": "США",
    "india": "Индия",
    "united-kingdom": "Великобритания",
    "china": "Китай",
    "germany": "Германия",
    "france": "Франция",
    "japao": "Япония",
    "remoto-global": "Удалённо",
    "singapura": "Сингапур",
    "sweden": "Швеция",
    "coreia-do-sul": "Южная Корея",
    "spain": "Испания",
    "netherlands": "Нидерланды",
    "poland": "Польша",
    "ireland": "Ирландия",
    "finland": "Финляндия",
    "portugal": "Португалия",
    "switzerland": "Швейцария",
    "italy": "Италия",
    "denmark": "Дания",
    "norway": "Норвегия",
    "hong-kong": "Гонконг",
    "belgium": "Бельгия",
    "taiwan": "Тайвань",
    "indonesia": "Индонезия",
    "tailandia": "Таиланд",
    "malasia": "Малайзия",
    "austria": "Австрия",
    "vietna": "Вьетнам",
    "filipinas": "Филиппины",
    "estonia": "Эстония",
    "czech-republic": "Чехия",
    "romania": "Румыния",
    "hungary": "Венгрия",
    "luxembourg": "Люксембург",
    "ukraine": "Украина",
    "greece": "Греция",
    "paquistao": "Пакистан",
    "lithuania": "Литва",
    "sri-lanka": "Шри-Ланка",
    "bulgaria": "Болгария",
    "cyprus": "Кипр",
    "croatia": "Хорватия",
    "serbia": "Сербия",
    "slovakia": "Словакия",
    "malta": "Мальта",
    "iceland": "Исландия",
    "slovenia": "Словения",
    "bangladesh": "Бангладеш",
    "latvia": "Латвия",
    "nepal": "Непал",
    "moldova": "Молдова",
    "georgia": "Грузия",
    "albania": "Албания",
    "north-macedonia": "Северная Македония",
    "bosnia-and-herzegovina": "Босния и Герцеговина",
    "montenegro": "Черногория",
  },
};

// Singular form of "countries" per language
export const COUNTRY_ONE: Record<string, string> = {
  en: "country",
  "pt-br": "país",
  "pt-pt": "país",
  es: "país",
  fr: "pays",
  de: "Land",
  it: "paese",
  nl: "land",
  pl: "kraj",
  ru: "страна",
  zh: "个国家",
  ja: "カ国",
  ko: "개국",
  hi: "देश",
  bn: "দেশ",
  ar: "دولة",
  tr: "ülke",
  vi: "quốc gia",
  th: "ประเทศ",
  ur: "مملکت",
  tl: "bansa",
  sw: "nchi",
};

export function getCountryNameTranslated(slug: string, lang: string, fallback: string): string {
  return COUNTRY_NAMES[lang]?.[slug] || fallback;
}

export function getCountryCountLabel(count: number, lang: string, plural: string): string {
  if (count === 1) {
    const one = COUNTRY_ONE[lang] || "country";
    return "1 " + one;
  }
  return count + " " + plural;
}
