// Mapa PT-BR/PT-PT dos países do catálogo mundial (nomes INTEIROS,
// sem abreviações) — gerado por scripts/gen-countries-full.py.
// Para outros idiomas o fallback é o campo `name` (EN) do catálogo.

export const COUNTRY_PT_FULL: Record<string, string> = {
  "afghanistan": "Afeganistão",
  "south-africa": "África do Sul",
  "albania": "Albânia",
  "germany": "Alemanha",
  "andorra": "Andorra",
  "angola": "Angola",
  "antigua-and-barbuda": "Antígua e Barbuda",
  "saudi-arabia": "Arábia Saudita",
  "algeria": "Argélia",
  "argentina": "Argentina",
  "armenia": "Armênia",
  "australia": "Austrália",
  "austria": "Áustria",
  "azerbaijan": "Azerbaijão",
  "bahamas": "Bahamas",
  "bangladesh": "Bangladesh",
  "barbados": "Barbados",
  "bahrain": "Barein",
  "belgium": "Bélgica",
  "belize": "Belize",
  "benin": "Benin",
  "belarus": "Bielorrússia",
  "bolivia": "Bolívia",
  "bosnia-and-herzegovina": "Bósnia e Herzegovina",
  "botswana": "Botsuana",
  "brazil": "Brasil",
  "brunei": "Brunei",
  "bulgaria": "Bulgária",
  "burkina-faso": "Burkina Faso",
  "burundi": "Burundi",
  "bhutan": "Butão",
  "cabo-verde": "Cabo Verde",
  "cameroon": "Camarões",
  "cambodia": "Camboja",
  "canada": "Canadá",
  "qatar": "Catar",
  "kazakhstan": "Cazaquistão",
  "chad": "Chade",
  "chile": "Chile",
  "china": "China",
  "cyprus": "Chipre",
  "colombia": "Colômbia",
  "comoros": "Comores",
  "north-korea": "Coreia do Norte",
  "coreia-do-sul": "Coreia do Sul",
  "ivory-coast": "Costa do Marfim",
  "costa-rica": "Costa Rica",
  "croatia": "Croácia",
  "cuba": "Cuba",
  "denmark": "Dinamarca",
  "djibouti": "Djibuti",
  "dominica": "Dominica",
  "egypt": "Egito",
  "el-salvador": "El Salvador",
  "united-arab-emirates": "Emirados Árabes Unidos",
  "ecuador": "Equador",
  "eritrea": "Eritreia",
  "slovakia": "Eslováquia",
  "slovenia": "Eslovênia",
  "spain": "Espanha",
  "united-states": "Estados Unidos",
  "estonia": "Estônia",
  "eswatini": "Eswatini",
  "ethiopia": "Etiópia",
  "fiji": "Fiji",
  "filipinas": "Filipinas",
  "finland": "Finlândia",
  "france": "França",
  "gabon": "Gabão",
  "gambia": "Gâmbia",
  "ghana": "Gana",
  "georgia": "Geórgia",
  "grenada": "Granada",
  "greece": "Grécia",
  "guatemala": "Guatemala",
  "guyana": "Guiana",
  "guinea": "Guiné",
  "guinea-bissau": "Guiné-Bissau",
  "equatorial-guinea": "Guiné Equatorial",
  "haiti": "Haiti",
  "honduras": "Honduras",
  "hungary": "Hungria",
  "yemen": "Iêmen",
  "marshall-islands": "Ilhas Marshall",
  "solomon-islands": "Ilhas Salomão",
  "india": "Índia",
  "indonesia": "Indonésia",
  "iran": "Irã",
  "iraq": "Iraque",
  "ireland": "Irlanda",
  "iceland": "Islândia",
  "israel": "Israel",
  "italy": "Itália",
  "jamaica": "Jamaica",
  "japao": "Japão",
  "jordan": "Jordânia",
  "kiribati": "Kiribati",
  "kuwait": "Kuwait",
  "laos": "Laos",
  "lesotho": "Lesoto",
  "latvia": "Letônia",
  "lebanon": "Líbano",
  "liberia": "Libéria",
  "libya": "Líbia",
  "liechtenstein": "Liechtenstein",
  "lithuania": "Lituânia",
  "luxembourg": "Luxemburgo",
  "north-macedonia": "Macedônia do Norte",
  "madagascar": "Madagascar",
  "malasia": "Malásia",
  "malawi": "Malaui",
  "maldives": "Maldivas",
  "mali": "Mali",
  "malta": "Malta",
  "morocco": "Marrocos",
  "mauritius": "Maurício",
  "mauritania": "Mauritânia",
  "mexico": "México",
  "myanmar": "Mianmar",
  "micronesia": "Micronésia",
  "mozambique": "Moçambique",
  "moldova": "Moldávia",
  "monaco": "Mônaco",
  "mongolia": "Mongólia",
  "montenegro": "Montenegro",
  "namibia": "Namíbia",
  "nauru": "Nauru",
  "nepal": "Nepal",
  "nicaragua": "Nicarágua",
  "niger": "Níger",
  "nigeria": "Nigéria",
  "norway": "Noruega",
  "nova-zelandia": "Nova Zelândia",
  "oman": "Omã",
  "netherlands": "Países Baixos",
  "palau": "Palau",
  "palestine": "Palestina",
  "panama": "Panamá",
  "papua-new-guinea": "Papua-Nova Guiné",
  "paquistao": "Paquistão",
  "paraguay": "Paraguai",
  "peru": "Peru",
  "poland": "Polônia",
  "portugal": "Portugal",
  "kenya": "Quênia",
  "kyrgyzstan": "Quirguistão",
  "united-kingdom": "Reino Unido",
  "central-african-republic": "República Centro-Africana",
  "dr-congo": "República Democrática do Congo",
  "republic-of-the-congo": "República do Congo",
  "dominican-republic": "República Dominicana",
  "czech-republic": "República Tcheca",
  "romania": "Romênia",
  "rwanda": "Ruanda",
  "russia": "Rússia",
  "samoa": "Samoa",
  "san-marino": "San Marino",
  "saint-lucia": "Santa Lúcia",
  "saint-kitts-and-nevis": "São Cristóvão e Névis",
  "sao-tome-and-principe": "São Tomé e Príncipe",
  "saint-vincent-and-the-grenadines": "São Vicente e Granadinas",
  "senegal": "Senegal",
  "sierra-leone": "Serra Leoa",
  "serbia": "Sérvia",
  "seychelles": "Seicheles",
  "singapura": "Singapura",
  "syria": "Síria",
  "somalia": "Somália",
  "sri-lanka": "Sri Lanka",
  "sudan": "Sudão",
  "south-sudan": "Sudão do Sul",
  "sweden": "Suécia",
  "switzerland": "Suíça",
  "suriname": "Suriname",
  "tajikistan": "Tadjiquistão",
  "tailandia": "Tailândia",
  "taiwan": "Taiwan",
  "tanzania": "Tanzânia",
  "timor-leste": "Timor-Leste",
  "togo": "Togo",
  "tonga": "Tonga",
  "trinidad-and-tobago": "Trinidad e Tobago",
  "tunisia": "Tunísia",
  "turkmenistan": "Turcomenistão",
  "turkey": "Turquia",
  "tuvalu": "Tuvalu",
  "ukraine": "Ucrânia",
  "uganda": "Uganda",
  "uruguay": "Uruguai",
  "uzbekistan": "Uzbequistão",
  "vanuatu": "Vanuatu",
  "vatican-city": "Vaticano",
  "venezuela": "Venezuela",
  "vietna": "Vietnã",
  "zambia": "Zâmbia",
  "zimbabwe": "Zimbábue",
  "hong-kong": "Hong Kong",
  "remoto-global": "Remoto Global",
};
