import { NextResponse } from "next/server";

export interface Job {
  id: number; title: string; company: string; companyUrl: string;
  location: string; country: string; countryName: string;
  lat: number; lng: number;
  salary: string; salaryMin: number; salaryMax: number;
  salaryCurrency: string; salaryPeriod: string;
  description: string; sector: string; posted: string; type: string;
  contactEmail: string;
  paywall: boolean;
}

export const jobs: Job[] = [
  {
    id: 1, title: "Registered Nurse", company: "Johnson & Johnson",
    companyUrl: "https://jnj.com/careers", location: "New York, NY",
    country: "us", countryName: "United States",
    lat: 40.7128, lng: -74.006,
    salary: "$233,737/yr", salaryMin: 85495, salaryMax: 233737,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Provide high-quality patient care and collaborate with multidisciplinary medical teams. Contribute to clinical research and quality improvement initiatives.",
    sector: "Healthcare", posted: "1 week ago", type: "Part-time",
    contactEmail: "careers@johnson&johnson.com",
    paywall: false,
  },

  {
    id: 2, title: "Sales Manager", company: "Adobe",
    companyUrl: "https://adobe.com/careers", location: "Denver, CO",
    country: "us", countryName: "United States",
    lat: 39.7392, lng: -104.9903,
    salary: "$273,593/yr", salaryMin: 91463, salaryMax: 273593,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Drive revenue growth by identifying and closing enterprise deals. Build relationships with C-suite executives and manage the full sales cycle from prospecting to close.",
    sector: "Sales", posted: "2 days ago", type: "Internship",
    contactEmail: "careers@adobe.com",
    paywall: false,
  },

  {
    id: 3, title: "Product Designer", company: "Figma",
    companyUrl: "https://figma.com/careers", location: "Chicago, IL",
    country: "us", countryName: "United States",
    lat: 41.8781, lng: -87.6298,
    salary: "$267,572/yr", salaryMin: 83221, salaryMax: 267572,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Lead the visual identity and design system for the product. Ensure brand consistency across all touchpoints and mentor the design team.",
    sector: "Design", posted: "4 days ago", type: "Part-time",
    contactEmail: "careers@figma.com",
    paywall: true,
  },

  {
    id: 4, title: "Academic Researcher", company: "Coursera",
    companyUrl: "https://coursera.org/careers", location: "Boston, MA",
    country: "us", countryName: "United States",
    lat: 42.3601, lng: -71.0589,
    salary: "$273,291/yr", salaryMin: 89671, salaryMax: 273291,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Develop innovative curriculum and learning materials for online and in-person programs. Leverage technology to create engaging educational experiences.",
    sector: "Education", posted: "5 days ago", type: "Internship",
    contactEmail: "careers@coursera.com",
    paywall: false,
  },

  {
    id: 5, title: "Chemical Engineer", company: "Tesla",
    companyUrl: "https://tesla.com/careers", location: "New York, NY",
    country: "us", countryName: "United States",
    lat: 40.7128, lng: -74.006,
    salary: "$276,211/yr", salaryMin: 93427, salaryMax: 276211,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Develop innovative engineering solutions for complex technical challenges. Lead testing, validation, and quality assurance processes.",
    sector: "Engineering", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@tesla.com",
    paywall: false,
  },

  {
    id: 6, title: "Product Manager", company: "McKinsey",
    companyUrl: "https://mckinsey.com/careers", location: "Austin, TX",
    country: "us", countryName: "United States",
    lat: 30.2672, lng: -97.7431,
    salary: "$279,608/yr", salaryMin: 65458, salaryMax: 279608,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Own the product roadmap and prioritize features based on user research and business impact. Manage cross-functional teams and drive product launches.",
    sector: "Management", posted: "4 days ago", type: "Contract",
    contactEmail: "careers@mckinsey.com",
    paywall: false,
  },

  {
    id: 7, title: "Compensation Analyst", company: "Gusto",
    companyUrl: "https://gusto.com/careers", location: "Boston, MA",
    country: "us", countryName: "United States",
    lat: 42.3601, lng: -71.0589,
    salary: "$214,066/yr", salaryMin: 103520, salaryMax: 214066,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "1 week ago", type: "Part-time",
    contactEmail: "careers@gusto.com",
    paywall: false,
  },

  {
    id: 8, title: "Brand Manager", company: "Netflix",
    companyUrl: "https://netflix.com/careers", location: "Seattle, WA",
    country: "us", countryName: "United States",
    lat: 47.6062, lng: -122.3321,
    salary: "$188,917/yr", salaryMin: 87087, salaryMax: 188917,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@netflix.com",
    paywall: false,
  },

  {
    id: 9, title: "NLP Engineer", company: "Palantir",
    companyUrl: "https://palantir.com/careers", location: "Boston, MA",
    country: "us", countryName: "United States",
    lat: 42.3601, lng: -71.0589,
    salary: "$275,215/yr", salaryMin: 85021, salaryMax: 275215,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Build predictive models and analyze large datasets to drive business decisions. Use Python, TensorFlow, and SQL to extract insights and present findings to leadership.",
    sector: "Data Science", posted: "4 days ago", type: "Full-time",
    contactEmail: "careers@palantir.com",
    paywall: false,
  },

  {
    id: 10, title: "Full Stack Developer", company: "Apple",
    companyUrl: "https://apple.com/careers", location: "Austin, TX",
    country: "us", countryName: "United States",
    lat: 30.2672, lng: -97.7431,
    salary: "$195,369/yr", salaryMin: 96245, salaryMax: 195369,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Lead the design and implementation of microservices architecture. Mentor junior engineers and drive technical decisions across multiple product teams.",
    sector: "Technology", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@apple.com",
    paywall: false,
  },

  {
    id: 11, title: "Risk Manager", company: "Goldman Sachs",
    companyUrl: "https://goldmansachs.com/careers", location: "Chicago, IL",
    country: "us", countryName: "United States",
    lat: 41.8781, lng: -87.6298,
    salary: "$265,147/yr", salaryMin: 87325, salaryMax: 265147,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Manage risk assessment frameworks and ensure regulatory compliance across multiple jurisdictions. Develop strategies to mitigate financial and operational risks.",
    sector: "Finance", posted: "4 days ago", type: "Part-time",
    contactEmail: "careers@goldmansachs.com",
    paywall: false,
  },

  {
    id: 12, title: "Compliance Officer", company: "Latham Watkins",
    companyUrl: "https://lathamwatkins.com/careers", location: "Austin, TX",
    country: "us", countryName: "United States",
    lat: 30.2672, lng: -97.7431,
    salary: "$232,186/yr", salaryMin: 121784, salaryMax: 232186,
    salaryCurrency: "USD", salaryPeriod: "year",
    description: "Provide expert legal counsel on corporate transactions, M&A deals, and regulatory matters. Draft and negotiate complex commercial agreements.",
    sector: "Legal", posted: "1 day ago", type: "Part-time",
    contactEmail: "careers@lathamwatkins.com",
    paywall: false,
  },

  {
    id: 13, title: "Senior Software Engineer", company: "Revolut",
    companyUrl: "https://revolut.com/careers", location: "Leeds",
    country: "gb", countryName: "United Kingdom",
    lat: 53.8008, lng: -1.5491,
    salary: "£177,881/yr", salaryMin: 79676, salaryMax: 177881,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Design and implement user-facing features using React, TypeScript, and modern web frameworks. Optimize performance and deliver pixel-perfect interfaces for global users.",
    sector: "Technology", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@revolut.com",
    paywall: false,
  },

  {
    id: 14, title: "Pharmacist", company: "GSK",
    companyUrl: "https://gsk.com/careers", location: "Birmingham",
    country: "gb", countryName: "United Kingdom",
    lat: 52.4862, lng: -1.8904,
    salary: "£107,925/yr", salaryMin: 64735, salaryMax: 107925,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "2 days ago", type: "Part-time",
    contactEmail: "careers@gsk.com",
    paywall: false,
  },

  {
    id: 15, title: "Systems Engineer", company: "Rolls-Royce",
    companyUrl: "https://rolls-royce.com/careers", location: "Edinburgh",
    country: "gb", countryName: "United Kingdom",
    lat: 55.9533, lng: -3.1883,
    salary: "£133,571/yr", salaryMin: 74909, salaryMax: 133571,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Design and oversee construction projects from conception to completion. Ensure compliance with safety standards and manage engineering teams on-site.",
    sector: "Engineering", posted: "2 days ago", type: "Internship",
    contactEmail: "careers@rolls-royce.com",
    paywall: false,
  },

  {
    id: 16, title: "Key Account Manager", company: "SAP UK",
    companyUrl: "https://sap.com/careers", location: "Edinburgh",
    country: "gb", countryName: "United Kingdom",
    lat: 55.9533, lng: -3.1883,
    salary: "£122,162/yr", salaryMin: 36276, salaryMax: 122162,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Develop strategic partnerships and expand market presence. Lead a team of sales representatives to exceed quarterly targets.",
    sector: "Sales", posted: "3 days ago", type: "Remote",
    contactEmail: "careers@sapuk.com",
    paywall: false,
  },

  {
    id: 17, title: "Data Scientist", company: "Quantcast",
    companyUrl: "https://quantcast.com/careers", location: "Manchester",
    country: "gb", countryName: "United Kingdom",
    lat: 53.4808, lng: -2.2426,
    salary: "£118,726/yr", salaryMin: 40161, salaryMax: 118726,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "5 days ago", type: "Internship",
    contactEmail: "careers@quantcast.com",
    paywall: false,
  },

  {
    id: 18, title: "E-learning Specialist", company: "Open University",
    companyUrl: "https://open.ac.uk/careers", location: "Leeds",
    country: "gb", countryName: "United Kingdom",
    lat: 53.8008, lng: -1.5491,
    salary: "£129,143/yr", salaryMin: 71031, salaryMax: 129143,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Manage educational technology platforms and ensure seamless learning experiences. Analyze student data to improve course outcomes.",
    sector: "Education", posted: "5 days ago", type: "Remote",
    contactEmail: "careers@openuniversity.com",
    paywall: false,
  },

  {
    id: 19, title: "Growth Hacker", company: "Diageo",
    companyUrl: "https://diageo.com/careers", location: "Bristol",
    country: "gb", countryName: "United Kingdom",
    lat: 51.4545, lng: -2.5879,
    salary: "£148,357/yr", salaryMin: 81723, salaryMax: 148357,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "1 week ago", type: "Part-time",
    contactEmail: "careers@diageo.com",
    paywall: false,
  },

  {
    id: 20, title: "Wealth Manager", company: "HSBC",
    companyUrl: "https://hsbc.com/careers", location: "Bristol",
    country: "gb", countryName: "United Kingdom",
    lat: 51.4545, lng: -2.5879,
    salary: "£139,993/yr", salaryMin: 42930, salaryMax: 139993,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Analyze financial statements and market trends to support investment decisions. Prepare detailed reports for C-level stakeholders and present quarterly performance reviews.",
    sector: "Finance", posted: "1 day ago", type: "Remote",
    contactEmail: "careers@hsbc.com",
    paywall: true,
  },

  {
    id: 21, title: "Strategy Consultant", company: "PwC UK",
    companyUrl: "https://pwc.co.uk/careers", location: "Manchester",
    country: "gb", countryName: "United Kingdom",
    lat: 53.4808, lng: -2.2426,
    salary: "£115,216/yr", salaryMin: 39652, salaryMax: 115216,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Own the product roadmap and prioritize features based on user research and business impact. Manage cross-functional teams and drive product launches.",
    sector: "Management", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@pwcuk.com",
    paywall: true,
  },

  {
    id: 22, title: "HR Business Partner", company: "Michael Page",
    companyUrl: "https://michaelpage.com/careers", location: "Bristol",
    country: "gb", countryName: "United Kingdom",
    lat: 51.4545, lng: -2.5879,
    salary: "£171,124/yr", salaryMin: 53250, salaryMax: 171124,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "1 week ago", type: "Part-time",
    contactEmail: "careers@michaelpage.com",
    paywall: false,
  },

  {
    id: 23, title: "Legal Counsel", company: "Allen Overy",
    companyUrl: "https://allenovery.com/careers", location: "Birmingham",
    country: "gb", countryName: "United Kingdom",
    lat: 52.4862, lng: -1.8904,
    salary: "£119,863/yr", salaryMin: 47478, salaryMax: 119863,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Provide expert legal counsel on corporate transactions, M&A deals, and regulatory matters. Draft and negotiate complex commercial agreements.",
    sector: "Legal", posted: "3 days ago", type: "Remote",
    contactEmail: "careers@allenovery.com",
    paywall: false,
  },

  {
    id: 24, title: "Design Lead", company: "Shazam",
    companyUrl: "https://shazam.com/careers", location: "Birmingham",
    country: "gb", countryName: "United Kingdom",
    lat: 52.4862, lng: -1.8904,
    salary: "£120,399/yr", salaryMin: 79129, salaryMax: 120399,
    salaryCurrency: "GBP", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@shazam.com",
    paywall: false,
  },

  {
    id: 25, title: "Enterprise Sales Lead", company: "Siemens Healthineers",
    companyUrl: "https://siemens-healthineers.com/careers", location: "Stuttgart",
    country: "de", countryName: "Germany",
    lat: 48.7758, lng: 9.1829,
    salary: "€142,738/yr", salaryMin: 43315, salaryMax: 142738,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Drive revenue growth by identifying and closing enterprise deals. Build relationships with C-suite executives and manage the full sales cycle from prospecting to close.",
    sector: "Sales", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@siemenshealthineers.com",
    paywall: false,
  },

  {
    id: 26, title: "Mobile Developer", company: "SAP",
    companyUrl: "https://sap.com/careers", location: "Hamburg",
    country: "de", countryName: "Germany",
    lat: 53.5511, lng: 9.9937,
    salary: "€156,665/yr", salaryMin: 54008, salaryMax: 156665,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Design and implement user-facing features using React, TypeScript, and modern web frameworks. Optimize performance and deliver pixel-perfect interfaces for global users.",
    sector: "Technology", posted: "2 days ago", type: "Remote",
    contactEmail: "careers@sap.com",
    paywall: false,
  },

  {
    id: 27, title: "Data Scientist", company: "Celonis",
    companyUrl: "https://celonis.com/careers", location: "Hamburg",
    country: "de", countryName: "Germany",
    lat: 53.5511, lng: 9.9937,
    salary: "€118,694/yr", salaryMin: 69819, salaryMax: 118694,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "1 week ago", type: "Contract",
    contactEmail: "careers@celonis.com",
    paywall: false,
  },

  {
    id: 28, title: "UI Designer", company: "Porsche Design",
    companyUrl: "https://porsche.com/careers", location: "Munich",
    country: "de", countryName: "Germany",
    lat: 48.1351, lng: 11.582,
    salary: "€103,832/yr", salaryMin: 54267, salaryMax: 103832,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "1 day ago", type: "Contract",
    contactEmail: "careers@porschedesign.com",
    paywall: false,
  },

  {
    id: 29, title: "Strategy Consultant", company: "McKinsey DE",
    companyUrl: "https://mckinsey.de/careers", location: "Hamburg",
    country: "de", countryName: "Germany",
    lat: 53.5511, lng: 9.9937,
    salary: "€110,317/yr", salaryMin: 74807, salaryMax: 110317,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Own the product roadmap and prioritize features based on user research and business impact. Manage cross-functional teams and drive product launches.",
    sector: "Management", posted: "1 day ago", type: "Internship",
    contactEmail: "careers@mckinseyde.com",
    paywall: false,
  },

  {
    id: 30, title: "Curriculum Developer", company: "Humboldt University",
    companyUrl: "https://hu-berlin.de/careers", location: "Stuttgart",
    country: "de", countryName: "Germany",
    lat: 48.7758, lng: 9.1829,
    salary: "€156,480/yr", salaryMin: 84250, salaryMax: 156480,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Develop innovative curriculum and learning materials for online and in-person programs. Leverage technology to create engaging educational experiences.",
    sector: "Education", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@humboldtuniversity.com",
    paywall: false,
  },

  {
    id: 31, title: "L&D Specialist", company: "Personio",
    companyUrl: "https://personio.com/careers", location: "Stuttgart",
    country: "de", countryName: "Germany",
    lat: 48.7758, lng: 9.1829,
    salary: "€105,372/yr", salaryMin: 80591, salaryMax: 105372,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Design compensation and benefits programs that attract and retain talent. Analyze market data and ensure competitive positioning.",
    sector: "HR", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@personio.com",
    paywall: false,
  },

  {
    id: 32, title: "Pharmacist", company: "Merck",
    companyUrl: "https://merck.com/careers", location: "Munich",
    country: "de", countryName: "Germany",
    lat: 48.1351, lng: 11.582,
    salary: "€117,407/yr", salaryMin: 55642, salaryMax: 117407,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "1 week ago", type: "Contract",
    contactEmail: "careers@merck.com",
    paywall: true,
  },

  {
    id: 33, title: "Chemical Engineer", company: "BMW Group",
    companyUrl: "https://bmwgroup.com/careers", location: "Frankfurt",
    country: "de", countryName: "Germany",
    lat: 50.1109, lng: 8.6821,
    salary: "€130,034/yr", salaryMin: 40610, salaryMax: 130034,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Design and oversee construction projects from conception to completion. Ensure compliance with safety standards and manage engineering teams on-site.",
    sector: "Engineering", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@bmwgroup.com",
    paywall: true,
  },

  {
    id: 34, title: "Legal Counsel", company: "Freshfields",
    companyUrl: "https://freshfields.com/careers", location: "Frankfurt",
    country: "de", countryName: "Germany",
    lat: 50.1109, lng: 8.6821,
    salary: "€124,217/yr", salaryMin: 56009, salaryMax: 124217,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Ensure organizational compliance with local and international regulations. Manage legal risk and advise on strategic business decisions.",
    sector: "Legal", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@freshfields.com",
    paywall: true,
  },

  {
    id: 35, title: "Brand Manager", company: "Lufthansa",
    companyUrl: "https://lufthansa.com/careers", location: "Dusseldorf",
    country: "de", countryName: "Germany",
    lat: 51.2277, lng: 6.7735,
    salary: "€143,769/yr", salaryMin: 40512, salaryMax: 143769,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "1 day ago", type: "Internship",
    contactEmail: "careers@lufthansa.com",
    paywall: false,
  },

  {
    id: 36, title: "Compliance Officer", company: "Deutsche Bank",
    companyUrl: "https://db.com/careers", location: "Berlin",
    country: "de", countryName: "Germany",
    lat: 52.52, lng: 13.405,
    salary: "€110,187/yr", salaryMin: 76256, salaryMax: 110187,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Manage risk assessment frameworks and ensure regulatory compliance across multiple jurisdictions. Develop strategies to mitigate financial and operational risks.",
    sector: "Finance", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@deutschebank.com",
    paywall: true,
  },

  {
    id: 37, title: "Program Manager", company: "Deloitte Canada",
    companyUrl: "https://deloitte.ca/careers", location: "Vancouver, BC",
    country: "ca", countryName: "Canada",
    lat: 49.2827, lng: -123.1207,
    salary: "C$156,077/yr", salaryMin: 55589, salaryMax: 156077,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Lead complex consulting engagements with Fortune 500 clients. Deliver actionable recommendations and manage project delivery across global teams.",
    sector: "Management", posted: "4 days ago", type: "Contract",
    contactEmail: "careers@deloittecanada.com",
    paywall: false,
  },

  {
    id: 38, title: "Curriculum Developer", company: "Udemy",
    companyUrl: "https://udemy.com/careers", location: "Toronto, ON",
    country: "ca", countryName: "Canada",
    lat: 43.6532, lng: -79.3832,
    salary: "C$109,861/yr", salaryMin: 80755, salaryMax: 109861,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Manage educational technology platforms and ensure seamless learning experiences. Analyze student data to improve course outcomes.",
    sector: "Education", posted: "2 days ago", type: "Part-time",
    contactEmail: "careers@udemy.com",
    paywall: false,
  },

  {
    id: 39, title: "Risk Manager", company: "TD Bank",
    companyUrl: "https://td.com/careers", location: "Toronto, ON",
    country: "ca", countryName: "Canada",
    lat: 43.6532, lng: -79.3832,
    salary: "C$166,415/yr", salaryMin: 68897, salaryMax: 166415,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Analyze financial statements and market trends to support investment decisions. Prepare detailed reports for C-level stakeholders and present quarterly performance reviews.",
    sector: "Finance", posted: "2 days ago", type: "Contract",
    contactEmail: "careers@tdbank.com",
    paywall: false,
  },

  {
    id: 40, title: "Systems Engineer", company: "SNC-Lavalin",
    companyUrl: "https://snclavalin.com/careers", location: "Toronto, ON",
    country: "ca", countryName: "Canada",
    lat: 43.6532, lng: -79.3832,
    salary: "C$165,442/yr", salaryMin: 81692, salaryMax: 165442,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Develop innovative engineering solutions for complex technical challenges. Lead testing, validation, and quality assurance processes.",
    sector: "Engineering", posted: "1 week ago", type: "Contract",
    contactEmail: "careers@snc-lavalin.com",
    paywall: false,
  },

  {
    id: 41, title: "Legal Counsel", company: "Blake Cassels",
    companyUrl: "https://blakes.com/careers", location: "Vancouver, BC",
    country: "ca", countryName: "Canada",
    lat: 49.2827, lng: -123.1207,
    salary: "C$109,124/yr", salaryMin: 72020, salaryMax: 109124,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Provide expert legal counsel on corporate transactions, M&A deals, and regulatory matters. Draft and negotiate complex commercial agreements.",
    sector: "Legal", posted: "3 days ago", type: "Part-time",
    contactEmail: "careers@blakecassels.com",
    paywall: false,
  },

  {
    id: 42, title: "QA Engineer", company: "BlackBerry",
    companyUrl: "https://blackberry.com/careers", location: "Vancouver, BC",
    country: "ca", countryName: "Canada",
    lat: 49.2827, lng: -123.1207,
    salary: "C$159,101/yr", salaryMin: 55433, salaryMax: 159101,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Lead the design and implementation of microservices architecture. Mentor junior engineers and drive technical decisions across multiple product teams.",
    sector: "Technology", posted: "1 day ago", type: "Contract",
    contactEmail: "careers@blackberry.com",
    paywall: true,
  },

  {
    id: 43, title: "UI Designer", company: "Hootsuite",
    companyUrl: "https://hootsuite.com/careers", location: "Vancouver, BC",
    country: "ca", countryName: "Canada",
    lat: 49.2827, lng: -123.1207,
    salary: "C$127,500/yr", salaryMin: 67915, salaryMax: 127500,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "1 week ago", type: "Remote",
    contactEmail: "careers@hootsuite.com",
    paywall: true,
  },

  {
    id: 44, title: "Clinical Researcher", company: "Sun Life",
    companyUrl: "https://sunlife.com/careers", location: "Montreal, QC",
    country: "ca", countryName: "Canada",
    lat: 45.5017, lng: -73.5673,
    salary: "C$158,180/yr", salaryMin: 49549, salaryMax: 158180,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "5 days ago", type: "Contract",
    contactEmail: "careers@sunlife.com",
    paywall: false,
  },

  {
    id: 45, title: "NLP Engineer", company: "Element AI",
    companyUrl: "https://elementai.com/careers", location: "Ottawa, ON",
    country: "ca", countryName: "Canada",
    lat: 45.4215, lng: -75.6972,
    salary: "C$115,059/yr", salaryMin: 46808, salaryMax: 115059,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "3 days ago", type: "Contract",
    contactEmail: "careers@elementai.com",
    paywall: true,
  },

  {
    id: 46, title: "Marketing Manager", company: "Bell Canada",
    companyUrl: "https://bell.ca/careers", location: "Ottawa, ON",
    country: "ca", countryName: "Canada",
    lat: 45.4215, lng: -75.6972,
    salary: "C$155,245/yr", salaryMin: 67654, salaryMax: 155245,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "5 days ago", type: "Remote",
    contactEmail: "careers@bellcanada.com",
    paywall: false,
  },

  {
    id: 47, title: "Enterprise Sales Lead", company: "Salesforce Canada",
    companyUrl: "https://salesforce.com/careers", location: "Ottawa, ON",
    country: "ca", countryName: "Canada",
    lat: 45.4215, lng: -75.6972,
    salary: "C$110,408/yr", salaryMin: 61693, salaryMax: 110408,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Develop strategic partnerships and expand market presence. Lead a team of sales representatives to exceed quarterly targets.",
    sector: "Sales", posted: "5 days ago", type: "Part-time",
    contactEmail: "careers@salesforcecanada.com",
    paywall: true,
  },

  {
    id: 48, title: "People Operations Manager", company: "Ceridian",
    companyUrl: "https://ceridian.com/careers", location: "Calgary, AB",
    country: "ca", countryName: "Canada",
    lat: 51.0447, lng: -114.0719,
    salary: "C$167,843/yr", salaryMin: 88531, salaryMax: 167843,
    salaryCurrency: "CAD", salaryPeriod: "year",
    description: "Design compensation and benefits programs that attract and retain talent. Analyze market data and ensure competitive positioning.",
    sector: "HR", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@ceridian.com",
    paywall: false,
  },

  {
    id: 49, title: "Systems Engineer", company: "Fortescue",
    companyUrl: "https://fortescue.com/careers", location: "Melbourne, VIC",
    country: "au", countryName: "Australia",
    lat: -37.8136, lng: 144.9631,
    salary: "A$161,946/yr", salaryMin: 92296, salaryMax: 161946,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Develop innovative engineering solutions for complex technical challenges. Lead testing, validation, and quality assurance processes.",
    sector: "Engineering", posted: "1 day ago", type: "Internship",
    contactEmail: "careers@fortescue.com",
    paywall: false,
  },

  {
    id: 50, title: "Business Development Rep", company: "BHP",
    companyUrl: "https://bhp.com/careers", location: "Melbourne, VIC",
    country: "au", countryName: "Australia",
    lat: -37.8136, lng: 144.9631,
    salary: "A$164,737/yr", salaryMin: 106495, salaryMax: 164737,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Develop strategic partnerships and expand market presence. Lead a team of sales representatives to exceed quarterly targets.",
    sector: "Sales", posted: "1 week ago", type: "Remote",
    contactEmail: "careers@bhp.com",
    paywall: false,
  },

  {
    id: 51, title: "Cybersecurity Analyst", company: "Atlassian",
    companyUrl: "https://atlassian.com/careers", location: "Perth, WA",
    country: "au", countryName: "Australia",
    lat: -31.9505, lng: 115.8605,
    salary: "A$133,614/yr", salaryMin: 98178, salaryMax: 133614,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Design and implement user-facing features using React, TypeScript, and modern web frameworks. Optimize performance and deliver pixel-perfect interfaces for global users.",
    sector: "Technology", posted: "1 week ago", type: "Part-time",
    contactEmail: "careers@atlassian.com",
    paywall: false,
  },

  {
    id: 52, title: "HR Business Partner", company: "SEEK",
    companyUrl: "https://seek.com.au/careers", location: "Melbourne, VIC",
    country: "au", countryName: "Australia",
    lat: -37.8136, lng: 144.9631,
    salary: "A$148,600/yr", salaryMin: 69722, salaryMax: 148600,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "2 days ago", type: "Contract",
    contactEmail: "careers@seek.com",
    paywall: true,
  },

  {
    id: 53, title: "Health Informatics Specialist", company: "Bupa",
    companyUrl: "https://bupa.com/careers", location: "Sydney, NSW",
    country: "au", countryName: "Australia",
    lat: -33.8688, lng: 151.2093,
    salary: "A$147,985/yr", salaryMin: 82160, salaryMax: 147985,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "2 days ago", type: "Remote",
    contactEmail: "careers@bupa.com",
    paywall: false,
  },

  {
    id: 54, title: "SEO Specialist", company: "Telstra",
    companyUrl: "https://telstra.com/careers", location: "Sydney, NSW",
    country: "au", countryName: "Australia",
    lat: -33.8688, lng: 151.2093,
    salary: "A$178,224/yr", salaryMin: 106014, salaryMax: 178224,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Develop and execute multi-channel marketing strategies to drive user acquisition and retention. Manage campaigns across digital platforms with measurable KPIs.",
    sector: "Marketing", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@telstra.com",
    paywall: true,
  },

  {
    id: 55, title: "UX Designer", company: "Canva Design",
    companyUrl: "https://canva.com/careers", location: "Canberra, ACT",
    country: "au", countryName: "Australia",
    lat: -35.2809, lng: 149.13,
    salary: "A$182,329/yr", salaryMin: 62953, salaryMax: 182329,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "1 week ago", type: "Part-time",
    contactEmail: "careers@canvadesign.com",
    paywall: false,
  },

  {
    id: 56, title: "Operations Director", company: "PwC Australia",
    companyUrl: "https://pwc.com.au/careers", location: "Canberra, ACT",
    country: "au", countryName: "Australia",
    lat: -35.2809, lng: 149.13,
    salary: "A$180,946/yr", salaryMin: 82966, salaryMax: 180946,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Own the product roadmap and prioritize features based on user research and business impact. Manage cross-functional teams and drive product launches.",
    sector: "Management", posted: "4 days ago", type: "Internship",
    contactEmail: "careers@pwcaustralia.com",
    paywall: false,
  },

  {
    id: 57, title: "Compliance Officer", company: "Allens",
    companyUrl: "https://allens.com.au/careers", location: "Melbourne, VIC",
    country: "au", countryName: "Australia",
    lat: -37.8136, lng: 144.9631,
    salary: "A$186,017/yr", salaryMin: 105188, salaryMax: 186017,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Provide expert legal counsel on corporate transactions, M&A deals, and regulatory matters. Draft and negotiate complex commercial agreements.",
    sector: "Legal", posted: "1 day ago", type: "Contract",
    contactEmail: "careers@allens.com",
    paywall: true,
  },

  {
    id: 58, title: "E-learning Specialist", company: "University of Melbourne",
    companyUrl: "https://unimelb.edu.au/careers", location: "Brisbane, QLD",
    country: "au", countryName: "Australia",
    lat: -27.4698, lng: 153.0251,
    salary: "A$133,061/yr", salaryMin: 75952, salaryMax: 133061,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Develop innovative curriculum and learning materials for online and in-person programs. Leverage technology to create engaging educational experiences.",
    sector: "Education", posted: "4 days ago", type: "Contract",
    contactEmail: "careers@universityofmelbourne.com",
    paywall: true,
  },

  {
    id: 59, title: "NLP Engineer", company: "CSIRO",
    companyUrl: "https://csiro.au/careers", location: "Melbourne, VIC",
    country: "au", countryName: "Australia",
    lat: -37.8136, lng: 144.9631,
    salary: "A$175,924/yr", salaryMin: 82188, salaryMax: 175924,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "4 days ago", type: "Full-time",
    contactEmail: "careers@csiro.com",
    paywall: false,
  },

  {
    id: 60, title: "Portfolio Manager", company: "Commonwealth Bank",
    companyUrl: "https://commbank.com.au/careers", location: "Perth, WA",
    country: "au", countryName: "Australia",
    lat: -31.9505, lng: 115.8605,
    salary: "A$125,060/yr", salaryMin: 105449, salaryMax: 125060,
    salaryCurrency: "AUD", salaryPeriod: "year",
    description: "Manage risk assessment frameworks and ensure regulatory compliance across multiple jurisdictions. Develop strategies to mitigate financial and operational risks.",
    sector: "Finance", posted: "3 days ago", type: "Remote",
    contactEmail: "careers@commonwealthbank.com",
    paywall: false,
  },

  {
    id: 61, title: "People Operations Manager", company: "PERSOL",
    companyUrl: "https://persol.co.jp/careers", location: "Yokohama",
    country: "jp", countryName: "Japan",
    lat: 35.4437, lng: 139.638,
    salary: "¥1,0570,000/yr", salaryMin: 7920752, salaryMax: 10570619,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "5 days ago", type: "Part-time",
    contactEmail: "careers@persol.com",
    paywall: false,
  },

  {
    id: 62, title: "QA Engineer", company: "Rakuten",
    companyUrl: "https://rakuten.co.jp/careers", location: "Tokyo",
    country: "jp", countryName: "Japan",
    lat: 35.6762, lng: 139.6503,
    salary: "¥1,0630,000/yr", salaryMin: 7595464, salaryMax: 10638329,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Design and implement user-facing features using React, TypeScript, and modern web frameworks. Optimize performance and deliver pixel-perfect interfaces for global users.",
    sector: "Technology", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@rakuten.com",
    paywall: true,
  },

  {
    id: 63, title: "Business Development Rep", company: "Honda",
    companyUrl: "https://honda.com/careers", location: "Osaka",
    country: "jp", countryName: "Japan",
    lat: 34.6937, lng: 135.5023,
    salary: "¥1,2330,000/yr", salaryMin: 6741781, salaryMax: 12331159,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Develop strategic partnerships and expand market presence. Lead a team of sales representatives to exceed quarterly targets.",
    sector: "Sales", posted: "4 days ago", type: "Remote",
    contactEmail: "careers@honda.com",
    paywall: true,
  },

  {
    id: 64, title: "Mechanical Engineer", company: "Mitsubishi Heavy",
    companyUrl: "https://mhps.com/careers", location: "Yokohama",
    country: "jp", countryName: "Japan",
    lat: 35.4437, lng: 139.638,
    salary: "¥1,2430,000/yr", salaryMin: 4436925, salaryMax: 12435680,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Design and oversee construction projects from conception to completion. Ensure compliance with safety standards and manage engineering teams on-site.",
    sector: "Engineering", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@mitsubishiheavy.com",
    paywall: false,
  },

  {
    id: 65, title: "UX Designer", company: "Nintendo",
    companyUrl: "https://nintendo.com/careers", location: "Osaka",
    country: "jp", countryName: "Japan",
    lat: 34.6937, lng: 135.5023,
    salary: "¥1,4710,000/yr", salaryMin: 4170959, salaryMax: 14712141,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "4 days ago", type: "Part-time",
    contactEmail: "careers@nintendo.com",
    paywall: true,
  },

  {
    id: 66, title: "Investment Banker", company: "SMBC",
    companyUrl: "https://smbc.co.jp/careers", location: "Nagoya",
    country: "jp", countryName: "Japan",
    lat: 35.1815, lng: 136.9066,
    salary: "¥1,1640,000/yr", salaryMin: 7900987, salaryMax: 11649527,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Manage risk assessment frameworks and ensure regulatory compliance across multiple jurisdictions. Develop strategies to mitigate financial and operational risks.",
    sector: "Finance", posted: "5 days ago", type: "Part-time",
    contactEmail: "careers@smbc.com",
    paywall: true,
  },

  {
    id: 67, title: "Medical Doctor", company: "Takeda",
    companyUrl: "https://takeda.com/careers", location: "Kyoto",
    country: "jp", countryName: "Japan",
    lat: 35.0116, lng: 135.7681,
    salary: "¥1,2110,000/yr", salaryMin: 4215406, salaryMax: 12116887,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@takeda.com",
    paywall: false,
  },

  {
    id: 68, title: "Marketing Manager", company: "Toyota Marketing",
    companyUrl: "https://toyota-global.com/careers", location: "Nagoya",
    country: "jp", countryName: "Japan",
    lat: 35.1815, lng: 136.9066,
    salary: "¥1,2020,000/yr", salaryMin: 4854810, salaryMax: 12029858,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Develop and execute multi-channel marketing strategies to drive user acquisition and retention. Manage campaigns across digital platforms with measurable KPIs.",
    sector: "Marketing", posted: "5 days ago", type: "Part-time",
    contactEmail: "careers@toyotamarketing.com",
    paywall: false,
  },

  {
    id: 69, title: "Academic Researcher", company: "Benesse",
    companyUrl: "https://benesse.jp/careers", location: "Nagoya",
    country: "jp", countryName: "Japan",
    lat: 35.1815, lng: 136.9066,
    salary: "¥1,0070,000/yr", salaryMin: 7108573, salaryMax: 10078451,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Manage educational technology platforms and ensure seamless learning experiences. Analyze student data to improve course outcomes.",
    sector: "Education", posted: "4 days ago", type: "Remote",
    contactEmail: "careers@benesse.com",
    paywall: true,
  },

  {
    id: 70, title: "Corporate Lawyer", company: "Nishimura Asahi",
    companyUrl: "https://nashimalaw.com/careers", location: "Yokohama",
    country: "jp", countryName: "Japan",
    lat: 35.4437, lng: 139.638,
    salary: "¥1,0780,000/yr", salaryMin: 7856573, salaryMax: 10783382,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Ensure organizational compliance with local and international regulations. Manage legal risk and advise on strategic business decisions.",
    sector: "Legal", posted: "5 days ago", type: "Contract",
    contactEmail: "careers@nishimuraasahi.com",
    paywall: true,
  },

  {
    id: 71, title: "Strategy Consultant", company: "McKinsey Japan",
    companyUrl: "https://mckinsey.jp/careers", location: "Nagoya",
    country: "jp", countryName: "Japan",
    lat: 35.1815, lng: 136.9066,
    salary: "¥1,3150,000/yr", salaryMin: 7899643, salaryMax: 13153863,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Lead complex consulting engagements with Fortune 500 clients. Deliver actionable recommendations and manage project delivery across global teams.",
    sector: "Management", posted: "2 days ago", type: "Remote",
    contactEmail: "careers@mckinseyjapan.com",
    paywall: false,
  },

  {
    id: 72, title: "ML Researcher", company: "Preferred Networks",
    companyUrl: "https://preferred-networks.jp/careers", location: "Yokohama",
    country: "jp", countryName: "Japan",
    lat: 35.4437, lng: 139.638,
    salary: "¥1,4280,000/yr", salaryMin: 7898257, salaryMax: 14280245,
    salaryCurrency: "JPY", salaryPeriod: "year",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "4 days ago", type: "Part-time",
    contactEmail: "careers@preferrednetworks.com",
    paywall: false,
  },

  {
    id: 73, title: "Senior Software Engineer", company: "IBM Zurich",
    companyUrl: "https://ibm.com/ch/careers", location: "Lausanne",
    country: "ch", countryName: "Switzerland",
    lat: 46.5197, lng: 6.6323,
    salary: "CHF191,635/yr", salaryMin: 81221, salaryMax: 191635,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Lead the design and implementation of microservices architecture. Mentor junior engineers and drive technical decisions across multiple product teams.",
    sector: "Technology", posted: "5 days ago", type: "Part-time",
    contactEmail: "careers@ibmzurich.com",
    paywall: false,
  },

  {
    id: 74, title: "Wealth Manager", company: "UBS",
    companyUrl: "https://ubs.com/careers", location: "Bern",
    country: "ch", countryName: "Switzerland",
    lat: 46.948, lng: 7.4474,
    salary: "CHF172,196/yr", salaryMin: 72260, salaryMax: 172196,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Manage risk assessment frameworks and ensure regulatory compliance across multiple jurisdictions. Develop strategies to mitigate financial and operational risks.",
    sector: "Finance", posted: "1 week ago", type: "Remote",
    contactEmail: "careers@ubs.com",
    paywall: true,
  },

  {
    id: 75, title: "Academic Researcher", company: "IMD",
    companyUrl: "https://imd.org/careers", location: "Lausanne",
    country: "ch", countryName: "Switzerland",
    lat: 46.5197, lng: 6.6323,
    salary: "CHF232,544/yr", salaryMin: 132031, salaryMax: 232544,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Manage educational technology platforms and ensure seamless learning experiences. Analyze student data to improve course outcomes.",
    sector: "Education", posted: "1 week ago", type: "Contract",
    contactEmail: "careers@imd.com",
    paywall: false,
  },

  {
    id: 76, title: "ML Researcher", company: "ETH Zurich",
    companyUrl: "https://ethz.ch/careers", location: "Bern",
    country: "ch", countryName: "Switzerland",
    lat: 46.948, lng: 7.4474,
    salary: "CHF192,951/yr", salaryMin: 110189, salaryMax: 192951,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Build predictive models and analyze large datasets to drive business decisions. Use Python, TensorFlow, and SQL to extract insights and present findings to leadership.",
    sector: "Data Science", posted: "2 days ago", type: "Contract",
    contactEmail: "careers@ethzurich.com",
    paywall: true,
  },

  {
    id: 77, title: "Mechanical Engineer", company: "Alstom",
    companyUrl: "https://alstom.com/careers", location: "Lausanne",
    country: "ch", countryName: "Switzerland",
    lat: 46.5197, lng: 6.6323,
    salary: "CHF188,361/yr", salaryMin: 95105, salaryMax: 188361,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Develop innovative engineering solutions for complex technical challenges. Lead testing, validation, and quality assurance processes.",
    sector: "Engineering", posted: "5 days ago", type: "Part-time",
    contactEmail: "careers@alstom.com",
    paywall: true,
  },

  {
    id: 78, title: "Corporate Lawyer", company: "Homburger",
    companyUrl: "https://homburger.ch/careers", location: "Geneva",
    country: "ch", countryName: "Switzerland",
    lat: 46.2044, lng: 6.1432,
    salary: "CHF207,301/yr", salaryMin: 99816, salaryMax: 207301,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Provide expert legal counsel on corporate transactions, M&A deals, and regulatory matters. Draft and negotiate complex commercial agreements.",
    sector: "Legal", posted: "1 week ago", type: "Contract",
    contactEmail: "careers@homburger.com",
    paywall: false,
  },

  {
    id: 79, title: "Program Manager", company: "McKinsey CH",
    companyUrl: "https://mckinsey.ch/careers", location: "Zurich",
    country: "ch", countryName: "Switzerland",
    lat: 47.3769, lng: 8.5417,
    salary: "CHF176,551/yr", salaryMin: 108290, salaryMax: 176551,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Lead complex consulting engagements with Fortune 500 clients. Deliver actionable recommendations and manage project delivery across global teams.",
    sector: "Management", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@mckinseych.com",
    paywall: true,
  },

  {
    id: 80, title: "Compensation Analyst", company: "Globe 24h",
    companyUrl: "https://globe24h.com/careers", location: "Bern",
    country: "ch", countryName: "Switzerland",
    lat: 46.948, lng: 7.4474,
    salary: "CHF184,164/yr", salaryMin: 114657, salaryMax: 184164,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "4 days ago", type: "Remote",
    contactEmail: "careers@globe24h.com",
    paywall: true,
  },

  {
    id: 81, title: "Marketing Manager", company: "Nestle",
    companyUrl: "https://nestle.com/careers", location: "Bern",
    country: "ch", countryName: "Switzerland",
    lat: 46.948, lng: 7.4474,
    salary: "CHF235,631/yr", salaryMin: 79710, salaryMax: 235631,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Develop and execute multi-channel marketing strategies to drive user acquisition and retention. Manage campaigns across digital platforms with measurable KPIs.",
    sector: "Marketing", posted: "5 days ago", type: "Remote",
    contactEmail: "careers@nestle.com",
    paywall: true,
  },

  {
    id: 82, title: "Registered Nurse", company: "Novartis",
    companyUrl: "https://novartis.com/careers", location: "Geneva",
    country: "ch", countryName: "Switzerland",
    lat: 46.2044, lng: 6.1432,
    salary: "CHF239,471/yr", salaryMin: 124548, salaryMax: 239471,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Provide high-quality patient care and collaborate with multidisciplinary medical teams. Contribute to clinical research and quality improvement initiatives.",
    sector: "Healthcare", posted: "4 days ago", type: "Full-time",
    contactEmail: "careers@novartis.com",
    paywall: false,
  },

  {
    id: 83, title: "Design Lead", company: "Rolex",
    companyUrl: "https://rolex.com/careers", location: "Basel",
    country: "ch", countryName: "Switzerland",
    lat: 47.5596, lng: 7.5886,
    salary: "CHF200,026/yr", salaryMin: 126207, salaryMax: 200026,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@rolex.com",
    paywall: false,
  },

  {
    id: 84, title: "Sales Manager", company: "Novartis",
    companyUrl: "https://novartis.com/careers", location: "Geneva",
    country: "ch", countryName: "Switzerland",
    lat: 46.2044, lng: 6.1432,
    salary: "CHF180,585/yr", salaryMin: 80641, salaryMax: 180585,
    salaryCurrency: "CHF", salaryPeriod: "year",
    description: "Drive revenue growth by identifying and closing enterprise deals. Build relationships with C-suite executives and manage the full sales cycle from prospecting to close.",
    sector: "Sales", posted: "1 day ago", type: "Contract",
    contactEmail: "careers@novartis.com",
    paywall: true,
  },

  {
    id: 85, title: "Account Executive", company: "Airbus",
    companyUrl: "https://airbus.com/careers", location: "Lyon",
    country: "fr", countryName: "France",
    lat: 45.764, lng: 4.8357,
    salary: "€124,652/yr", salaryMin: 72963, salaryMax: 124652,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Drive revenue growth by identifying and closing enterprise deals. Build relationships with C-suite executives and manage the full sales cycle from prospecting to close.",
    sector: "Sales", posted: "5 days ago", type: "Contract",
    contactEmail: "careers@airbus.com",
    paywall: false,
  },

  {
    id: 86, title: "NLP Engineer", company: "Criteo",
    companyUrl: "https://criteo.com/careers", location: "Lyon",
    country: "fr", countryName: "France",
    lat: 45.764, lng: 4.8357,
    salary: "€90,679/yr", salaryMin: 41321, salaryMax: 90679,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Build predictive models and analyze large datasets to drive business decisions. Use Python, TensorFlow, and SQL to extract insights and present findings to leadership.",
    sector: "Data Science", posted: "3 days ago", type: "Contract",
    contactEmail: "careers@criteo.com",
    paywall: true,
  },

  {
    id: 87, title: "Digital Marketing Lead", company: "Kering",
    companyUrl: "https://kering.com/careers", location: "Paris",
    country: "fr", countryName: "France",
    lat: 48.8566, lng: 2.3522,
    salary: "€131,857/yr", salaryMin: 51928, salaryMax: 131857,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "5 days ago", type: "Remote",
    contactEmail: "careers@kering.com",
    paywall: false,
  },

  {
    id: 88, title: "Chemical Engineer", company: "Alstom France",
    companyUrl: "https://alstom.com/careers", location: "Paris",
    country: "fr", countryName: "France",
    lat: 48.8566, lng: 2.3522,
    salary: "€114,313/yr", salaryMin: 34612, salaryMax: 114313,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Develop innovative engineering solutions for complex technical challenges. Lead testing, validation, and quality assurance processes.",
    sector: "Engineering", posted: "1 day ago", type: "Internship",
    contactEmail: "careers@alstomfrance.com",
    paywall: false,
  },

  {
    id: 89, title: "Portfolio Manager", company: "BNP Paribas",
    companyUrl: "https://bnpparibas.com/careers", location: "Bordeaux",
    country: "fr", countryName: "France",
    lat: 44.8378, lng: -0.5792,
    salary: "€136,119/yr", salaryMin: 33359, salaryMax: 136119,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Manage risk assessment frameworks and ensure regulatory compliance across multiple jurisdictions. Develop strategies to mitigate financial and operational risks.",
    sector: "Finance", posted: "2 days ago", type: "Internship",
    contactEmail: "careers@bnpparibas.com",
    paywall: false,
  },

  {
    id: 90, title: "Contract Specialist", company: "Gide",
    companyUrl: "https://gide.com/careers", location: "Toulouse",
    country: "fr", countryName: "France",
    lat: 43.6047, lng: 1.4442,
    salary: "€124,360/yr", salaryMin: 43894, salaryMax: 124360,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Ensure organizational compliance with local and international regulations. Manage legal risk and advise on strategic business decisions.",
    sector: "Legal", posted: "4 days ago", type: "Contract",
    contactEmail: "careers@gide.com",
    paywall: false,
  },

  {
    id: 91, title: "Compensation Analyst", company: "Manpower France",
    companyUrl: "https://manpower.fr/careers", location: "Marseille",
    country: "fr", countryName: "France",
    lat: 43.2965, lng: 5.3698,
    salary: "€107,040/yr", salaryMin: 53843, salaryMax: 107040,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "3 days ago", type: "Remote",
    contactEmail: "careers@manpowerfrance.com",
    paywall: false,
  },

  {
    id: 92, title: "Instructional Designer", company: "INSEAD",
    companyUrl: "https://insead.edu/careers", location: "Marseille",
    country: "fr", countryName: "France",
    lat: 43.2965, lng: 5.3698,
    salary: "€88,404/yr", salaryMin: 68051, salaryMax: 88404,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Manage educational technology platforms and ensure seamless learning experiences. Analyze student data to improve course outcomes.",
    sector: "Education", posted: "3 days ago", type: "Remote",
    contactEmail: "careers@insead.com",
    paywall: true,
  },

  {
    id: 93, title: "Registered Nurse", company: "Danone",
    companyUrl: "https://danone.com/careers", location: "Toulouse",
    country: "fr", countryName: "France",
    lat: 43.6047, lng: 1.4442,
    salary: "€129,100/yr", salaryMin: 32075, salaryMax: 129100,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "2 days ago", type: "Internship",
    contactEmail: "careers@danone.com",
    paywall: false,
  },

  {
    id: 94, title: "Strategy Consultant", company: "McKinsey France",
    companyUrl: "https://mckinsey.fr/careers", location: "Toulouse",
    country: "fr", countryName: "France",
    lat: 43.6047, lng: 1.4442,
    salary: "€99,340/yr", salaryMin: 35382, salaryMax: 99340,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Lead complex consulting engagements with Fortune 500 clients. Deliver actionable recommendations and manage project delivery across global teams.",
    sector: "Management", posted: "3 days ago", type: "Remote",
    contactEmail: "careers@mckinseyfrance.com",
    paywall: false,
  },

  {
    id: 95, title: "Tech Lead", company: "Thales",
    companyUrl: "https://thalesgroup.com/careers", location: "Toulouse",
    country: "fr", countryName: "France",
    lat: 43.6047, lng: 1.4442,
    salary: "€127,289/yr", salaryMin: 33891, salaryMax: 127289,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Lead the design and implementation of microservices architecture. Mentor junior engineers and drive technical decisions across multiple product teams.",
    sector: "Technology", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@thales.com",
    paywall: false,
  },

  {
    id: 96, title: "Product Designer", company: "L'Oreal Design",
    companyUrl: "https://loreal.com/careers", location: "Bordeaux",
    country: "fr", countryName: "France",
    lat: 44.8378, lng: -0.5792,
    salary: "€112,738/yr", salaryMin: 68192, salaryMax: 112738,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@lorealdesign.com",
    paywall: true,
  },

  {
    id: 97, title: "ML Engineer", company: "Booking.com",
    companyUrl: "https://booking.com/careers", location: "Eindhoven",
    country: "nl", countryName: "Netherlands",
    lat: 51.4416, lng: 5.4697,
    salary: "€106,491/yr", salaryMin: 63138, salaryMax: 106491,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Lead the design and implementation of microservices architecture. Mentor junior engineers and drive technical decisions across multiple product teams.",
    sector: "Technology", posted: "2 days ago", type: "Part-time",
    contactEmail: "careers@bookingcom.com",
    paywall: false,
  },

  {
    id: 98, title: "Program Manager", company: "PwC Netherlands",
    companyUrl: "https://pwc.nl/careers", location: "Utrecht",
    country: "nl", countryName: "Netherlands",
    lat: 52.0907, lng: 5.1214,
    salary: "€111,509/yr", salaryMin: 71275, salaryMax: 111509,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Own the product roadmap and prioritize features based on user research and business impact. Manage cross-functional teams and drive product launches.",
    sector: "Management", posted: "3 days ago", type: "Contract",
    contactEmail: "careers@pwcnetherlands.com",
    paywall: true,
  },

  {
    id: 99, title: "Legal Counsel", company: "De Brauw",
    companyUrl: "https://debrauw.com/careers", location: "Utrecht",
    country: "nl", countryName: "Netherlands",
    lat: 52.0907, lng: 5.1214,
    salary: "€116,618/yr", salaryMin: 69741, salaryMax: 116618,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Ensure organizational compliance with local and international regulations. Manage legal risk and advise on strategic business decisions.",
    sector: "Legal", posted: "5 days ago", type: "Internship",
    contactEmail: "careers@debrauw.com",
    paywall: false,
  },

  {
    id: 100, title: "Digital Marketing Lead", company: "Heineken",
    companyUrl: "https://heineken.com/careers", location: "The Hague",
    country: "nl", countryName: "Netherlands",
    lat: 52.0705, lng: 4.3007,
    salary: "€131,473/yr", salaryMin: 53650, salaryMax: 131473,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "4 days ago", type: "Part-time",
    contactEmail: "careers@heineken.com",
    paywall: true,
  },

  {
    id: 101, title: "Civil Engineer", company: "Shell",
    companyUrl: "https://shell.com/careers", location: "Utrecht",
    country: "nl", countryName: "Netherlands",
    lat: 52.0907, lng: 5.1214,
    salary: "€137,495/yr", salaryMin: 63302, salaryMax: 137495,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Design and oversee construction projects from conception to completion. Ensure compliance with safety standards and manage engineering teams on-site.",
    sector: "Engineering", posted: "1 day ago", type: "Remote",
    contactEmail: "careers@shell.com",
    paywall: false,
  },

  {
    id: 102, title: "Key Account Manager", company: "AkzoNobel",
    companyUrl: "https://akzonobel.com/careers", location: "Eindhoven",
    country: "nl", countryName: "Netherlands",
    lat: 51.4416, lng: 5.4697,
    salary: "€149,380/yr", salaryMin: 44577, salaryMax: 149380,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Develop strategic partnerships and expand market presence. Lead a team of sales representatives to exceed quarterly targets.",
    sector: "Sales", posted: "4 days ago", type: "Contract",
    contactEmail: "careers@akzonobel.com",
    paywall: true,
  },

  {
    id: 103, title: "E-learning Specialist", company: "TU Delft",
    companyUrl: "https://tudelft.nl/careers", location: "Utrecht",
    country: "nl", countryName: "Netherlands",
    lat: 52.0907, lng: 5.1214,
    salary: "€124,768/yr", salaryMin: 42903, salaryMax: 124768,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Manage educational technology platforms and ensure seamless learning experiences. Analyze student data to improve course outcomes.",
    sector: "Education", posted: "1 week ago", type: "Part-time",
    contactEmail: "careers@tudelft.com",
    paywall: false,
  },

  {
    id: 104, title: "NLP Engineer", company: "Elsevier",
    companyUrl: "https://elsevier.com/careers", location: "Amsterdam",
    country: "nl", countryName: "Netherlands",
    lat: 52.3676, lng: 4.9041,
    salary: "€128,971/yr", salaryMin: 82194, salaryMax: 128971,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "1 week ago", type: "Contract",
    contactEmail: "careers@elsevier.com",
    paywall: false,
  },

  {
    id: 105, title: "L&D Specialist", company: "Randstad",
    companyUrl: "https://randstad.com/careers", location: "Amsterdam",
    country: "nl", countryName: "Netherlands",
    lat: 52.3676, lng: 4.9041,
    salary: "€109,385/yr", salaryMin: 42484, salaryMax: 109385,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Design compensation and benefits programs that attract and retain talent. Analyze market data and ensure competitive positioning.",
    sector: "HR", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@randstad.com",
    paywall: false,
  },

  {
    id: 106, title: "Design Lead", company: "Philips Design",
    companyUrl: "https://philips.com/careers", location: "Amsterdam",
    country: "nl", countryName: "Netherlands",
    lat: 52.3676, lng: 4.9041,
    salary: "€104,902/yr", salaryMin: 67076, salaryMax: 104902,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Lead the visual identity and design system for the product. Ensure brand consistency across all touchpoints and mentor the design team.",
    sector: "Design", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@philipsdesign.com",
    paywall: false,
  },

  {
    id: 107, title: "Financial Analyst", company: "Rabobank",
    companyUrl: "https://rabobank.com/careers", location: "The Hague",
    country: "nl", countryName: "Netherlands",
    lat: 52.0705, lng: 4.3007,
    salary: "€122,225/yr", salaryMin: 62565, salaryMax: 122225,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Analyze financial statements and market trends to support investment decisions. Prepare detailed reports for C-level stakeholders and present quarterly performance reviews.",
    sector: "Finance", posted: "4 days ago", type: "Contract",
    contactEmail: "careers@rabobank.com",
    paywall: true,
  },

  {
    id: 108, title: "Medical Doctor", company: "Philips Healthcare",
    companyUrl: "https://philips.com/careers", location: "Rotterdam",
    country: "nl", countryName: "Netherlands",
    lat: 51.9244, lng: 4.4777,
    salary: "€119,070/yr", salaryMin: 77943, salaryMax: 119070,
    salaryCurrency: "EUR", salaryPeriod: "year",
    description: "Provide high-quality patient care and collaborate with multidisciplinary medical teams. Contribute to clinical research and quality improvement initiatives.",
    sector: "Healthcare", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@philipshealthcare.com",
    paywall: false,
  },

  {
    id: 109, title: "Operations Director", company: "McKinsey Singapore",
    companyUrl: "https://mckinsey.sg/careers", location: "Singapore Marina",
    country: "sg", countryName: "Singapore",
    lat: 1.2814, lng: 103.8636,
    salary: "S$176,615/yr", salaryMin: 61605, salaryMax: 176615,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Lead complex consulting engagements with Fortune 500 clients. Deliver actionable recommendations and manage project delivery across global teams.",
    sector: "Management", posted: "3 days ago", type: "Internship",
    contactEmail: "careers@mckinseysingapore.com",
    paywall: false,
  },

  {
    id: 110, title: "Instructional Designer", company: "NUS",
    companyUrl: "https://nus.edu.sg/careers", location: "Singapore Marina",
    country: "sg", countryName: "Singapore",
    lat: 1.2814, lng: 103.8636,
    salary: "S$170,986/yr", salaryMin: 57545, salaryMax: 170986,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Manage educational technology platforms and ensure seamless learning experiences. Analyze student data to improve course outcomes.",
    sector: "Education", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@nus.com",
    paywall: false,
  },

  {
    id: 111, title: "Financial Analyst", company: "OCBC",
    companyUrl: "https://ocbc.com/careers", location: "Singapore Jurong",
    country: "sg", countryName: "Singapore",
    lat: 1.3329, lng: 103.7436,
    salary: "S$122,061/yr", salaryMin: 59988, salaryMax: 122061,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Analyze financial statements and market trends to support investment decisions. Prepare detailed reports for C-level stakeholders and present quarterly performance reviews.",
    sector: "Finance", posted: "1 week ago", type: "Remote",
    contactEmail: "careers@ocbc.com",
    paywall: false,
  },

  {
    id: 112, title: "Compliance Officer", company: "Rajah Tann",
    companyUrl: "https://rajahtann.com/careers", location: "Singapore Central",
    country: "sg", countryName: "Singapore",
    lat: 1.2903, lng: 103.852,
    salary: "S$167,179/yr", salaryMin: 94555, salaryMax: 167179,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Provide expert legal counsel on corporate transactions, M&A deals, and regulatory matters. Draft and negotiate complex commercial agreements.",
    sector: "Legal", posted: "5 days ago", type: "Internship",
    contactEmail: "careers@rajahtann.com",
    paywall: false,
  },

  {
    id: 113, title: "QA Engineer", company: "Shopee",
    companyUrl: "https://shopee.com/careers", location: "Singapore Jurong",
    country: "sg", countryName: "Singapore",
    lat: 1.3329, lng: 103.7436,
    salary: "S$133,735/yr", salaryMin: 83172, salaryMax: 133735,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Lead the design and implementation of microservices architecture. Mentor junior engineers and drive technical decisions across multiple product teams.",
    sector: "Technology", posted: "3 days ago", type: "Part-time",
    contactEmail: "careers@shopee.com",
    paywall: false,
  },

  {
    id: 114, title: "Account Executive", company: "SingTel",
    companyUrl: "https://singtel.com/careers", location: "Singapore Jurong",
    country: "sg", countryName: "Singapore",
    lat: 1.3329, lng: 103.7436,
    salary: "S$138,224/yr", salaryMin: 89995, salaryMax: 138224,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Drive revenue growth by identifying and closing enterprise deals. Build relationships with C-suite executives and manage the full sales cycle from prospecting to close.",
    sector: "Sales", posted: "3 days ago", type: "Contract",
    contactEmail: "careers@singtel.com",
    paywall: false,
  },

  {
    id: 115, title: "Talent Acquisition Lead", company: "JobStreet SG",
    companyUrl: "https://jobstreet.com.sg/careers", location: "Singapore Central",
    country: "sg", countryName: "Singapore",
    lat: 1.2903, lng: 103.852,
    salary: "S$191,701/yr", salaryMin: 93544, salaryMax: 191701,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Design compensation and benefits programs that attract and retain talent. Analyze market data and ensure competitive positioning.",
    sector: "HR", posted: "3 days ago", type: "Part-time",
    contactEmail: "careers@jobstreetsg.com",
    paywall: false,
  },

  {
    id: 116, title: "Civil Engineer", company: "ST Engineering",
    companyUrl: "https://stengg.com/careers", location: "Singapore Marina",
    country: "sg", countryName: "Singapore",
    lat: 1.2814, lng: 103.8636,
    salary: "S$165,396/yr", salaryMin: 90926, salaryMax: 165396,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Design and oversee construction projects from conception to completion. Ensure compliance with safety standards and manage engineering teams on-site.",
    sector: "Engineering", posted: "1 day ago", type: "Contract",
    contactEmail: "careers@stengineering.com",
    paywall: false,
  },

  {
    id: 117, title: "Data Engineer", company: "GovTech",
    companyUrl: "https://tech.gov.sg/careers", location: "Singapore Jurong",
    country: "sg", countryName: "Singapore",
    lat: 1.3329, lng: 103.7436,
    salary: "S$194,048/yr", salaryMin: 97426, salaryMax: 194048,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "4 days ago", type: "Remote",
    contactEmail: "careers@govtech.com",
    paywall: true,
  },

  {
    id: 118, title: "Pharmacist", company: "SingHealth",
    companyUrl: "https://singhealth.com.sg/careers", location: "Singapore Jurong",
    country: "sg", countryName: "Singapore",
    lat: 1.3329, lng: 103.7436,
    salary: "S$169,311/yr", salaryMin: 71804, salaryMax: 169311,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@singhealth.com",
    paywall: false,
  },

  {
    id: 119, title: "Marketing Manager", company: "Singapore Airlines",
    companyUrl: "https://singaporeair.com/careers", location: "Singapore Jurong",
    country: "sg", countryName: "Singapore",
    lat: 1.3329, lng: 103.7436,
    salary: "S$124,280/yr", salaryMin: 72898, salaryMax: 124280,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "2 days ago", type: "Part-time",
    contactEmail: "careers@singaporeairlines.com",
    paywall: false,
  },

  {
    id: 120, title: "Brand Designer", company: "Razer Design",
    companyUrl: "https://razer.com/careers", location: "Singapore Marina",
    country: "sg", countryName: "Singapore",
    lat: 1.2814, lng: 103.8636,
    salary: "S$174,516/yr", salaryMin: 84548, salaryMax: 174516,
    salaryCurrency: "SGD", salaryPeriod: "year",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "1 day ago", type: "Contract",
    contactEmail: "careers@razerdesign.com",
    paywall: true,
  },

  {
    id: 121, title: "Mobile Developer", company: "Careem",
    companyUrl: "https://careem.com/careers", location: "Sharjah",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.3463, lng: 55.4209,
    salary: "AED54,173/mo", salaryMin: 24034, salaryMax: 54173,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Design and implement user-facing features using React, TypeScript, and modern web frameworks. Optimize performance and deliver pixel-perfect interfaces for global users.",
    sector: "Technology", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@careem.com",
    paywall: false,
  },

  {
    id: 122, title: "Brand Designer", company: "Emaar",
    companyUrl: "https://emaar.com/careers", location: "Abu Dhabi",
    country: "ae", countryName: "United Arab Emirates",
    lat: 24.4539, lng: 54.3773,
    salary: "AED48,571/mo", salaryMin: 22528, salaryMax: 48571,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Create intuitive user experiences through research-driven design. Conduct user interviews, build wireframes and prototypes, and collaborate with engineering to ship polished products.",
    sector: "Design", posted: "1 day ago", type: "Part-time",
    contactEmail: "careers@emaar.com",
    paywall: false,
  },

  {
    id: 123, title: "Key Account Manager", company: "Chalhoub Group",
    companyUrl: "https://chalhoubgroup.com/careers", location: "Sharjah",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.3463, lng: 55.4209,
    salary: "AED47,046/mo", salaryMin: 9984, salaryMax: 47046,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Develop strategic partnerships and expand market presence. Lead a team of sales representatives to exceed quarterly targets.",
    sector: "Sales", posted: "1 day ago", type: "Contract",
    contactEmail: "careers@chalhoubgroup.com",
    paywall: true,
  },

  {
    id: 124, title: "Product Manager", company: "McKinsey ME",
    companyUrl: "https://mckinsey.ae/careers", location: "Sharjah",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.3463, lng: 55.4209,
    salary: "AED34,699/mo", salaryMin: 27567, salaryMax: 34699,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Own the product roadmap and prioritize features based on user research and business impact. Manage cross-functional teams and drive product launches.",
    sector: "Management", posted: "2 days ago", type: "Part-time",
    contactEmail: "careers@mckinseyme.com",
    paywall: false,
  },

  {
    id: 125, title: "Contract Specialist", company: "Al Tamimi",
    companyUrl: "https://tamimi.com/careers", location: "Dubai",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.2048, lng: 55.2708,
    salary: "AED40,788/mo", salaryMin: 26160, salaryMax: 40788,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Provide expert legal counsel on corporate transactions, M&A deals, and regulatory matters. Draft and negotiate complex commercial agreements.",
    sector: "Legal", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@altamimi.com",
    paywall: false,
  },

  {
    id: 126, title: "E-learning Specialist", company: "NYU Abu Dhabi",
    companyUrl: "https://nyuad.nyu.edu/careers", location: "Sharjah",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.3463, lng: 55.4209,
    salary: "AED38,741/mo", salaryMin: 17085, salaryMax: 38741,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Develop innovative curriculum and learning materials for online and in-person programs. Leverage technology to create engaging educational experiences.",
    sector: "Education", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@nyuabudhabi.com",
    paywall: false,
  },

  {
    id: 127, title: "HR Business Partner", company: "Adecco Middle East",
    companyUrl: "https://adecco.com/careers", location: "Dubai",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.2048, lng: 55.2708,
    salary: "AED59,886/mo", salaryMin: 19738, salaryMax: 59886,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@adeccomiddleeast.com",
    paywall: false,
  },

  {
    id: 128, title: "Content Strategist", company: "Emirates Airlines",
    companyUrl: "https://emirates.com/careers", location: "Dubai",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.2048, lng: 55.2708,
    salary: "AED51,238/mo", salaryMin: 21794, salaryMax: 51238,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Develop and execute multi-channel marketing strategies to drive user acquisition and retention. Manage campaigns across digital platforms with measurable KPIs.",
    sector: "Marketing", posted: "4 days ago", type: "Part-time",
    contactEmail: "careers@emiratesairlines.com",
    paywall: false,
  },

  {
    id: 129, title: "Civil Engineer", company: "DP World",
    companyUrl: "https://dpworld.com/careers", location: "Sharjah",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.3463, lng: 55.4209,
    salary: "AED48,811/mo", salaryMin: 11573, salaryMax: 48811,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Design and oversee construction projects from conception to completion. Ensure compliance with safety standards and manage engineering teams on-site.",
    sector: "Engineering", posted: "1 day ago", type: "Internship",
    contactEmail: "careers@dpworld.com",
    paywall: false,
  },

  {
    id: 130, title: "Compliance Officer", company: "FAB",
    companyUrl: "https://bankfab.com/careers", location: "Abu Dhabi",
    country: "ae", countryName: "United Arab Emirates",
    lat: 24.4539, lng: 54.3773,
    salary: "AED49,695/mo", salaryMin: 9993, salaryMax: 49695,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Manage risk assessment frameworks and ensure regulatory compliance across multiple jurisdictions. Develop strategies to mitigate financial and operational risks.",
    sector: "Finance", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@fab.com",
    paywall: false,
  },

  {
    id: 131, title: "Biomedical Engineer", company: "Cleveland Clinic Abu Dhabi",
    companyUrl: "https://clevelandclinicabudhabi.com/careers", location: "Abu Dhabi",
    country: "ae", countryName: "United Arab Emirates",
    lat: 24.4539, lng: 54.3773,
    salary: "AED44,554/mo", salaryMin: 10647, salaryMax: 44554,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Provide high-quality patient care and collaborate with multidisciplinary medical teams. Contribute to clinical research and quality improvement initiatives.",
    sector: "Healthcare", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@clevelandclinicabudhabi.com",
    paywall: true,
  },

  {
    id: 132, title: "Analytics Manager", company: "DEWA",
    companyUrl: "https://dewa.gov.ae/careers", location: "Sharjah",
    country: "ae", countryName: "United Arab Emirates",
    lat: 25.3463, lng: 55.4209,
    salary: "AED48,867/mo", salaryMin: 17663, salaryMax: 48867,
    salaryCurrency: "AED", salaryPeriod: "month",
    description: "Design and maintain data pipelines and ETL processes. Build dashboards and reporting systems for real-time business intelligence.",
    sector: "Data Science", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@dewa.com",
    paywall: true,
  },

  {
    id: 133, title: "Tech Lead", company: "iFood",
    companyUrl: "https://ifood.com.br/careers", location: "Rio de Janeiro, RJ",
    country: "br", countryName: "Brazil",
    lat: -22.9068, lng: -43.1729,
    salary: "R$24,120/mo", salaryMin: 9992, salaryMax: 24120,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Lead the design and implementation of microservices architecture. Mentor junior engineers and drive technical decisions across multiple product teams.",
    sector: "Technology", posted: "2 days ago", type: "Contract",
    contactEmail: "careers@ifood.com",
    paywall: true,
  },

  {
    id: 134, title: "Data Scientist", company: "Stone",
    companyUrl: "https://stone.com.br/careers", location: "Rio de Janeiro, RJ",
    country: "br", countryName: "Brazil",
    lat: -22.9068, lng: -43.1729,
    salary: "R$26,075/mo", salaryMin: 4527, salaryMax: 26075,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Build predictive models and analyze large datasets to drive business decisions. Use Python, TensorFlow, and SQL to extract insights and present findings to leadership.",
    sector: "Data Science", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@stone.com",
    paywall: false,
  },

  {
    id: 135, title: "Key Account Manager", company: "Magazine Luiza",
    companyUrl: "https://magazineluiza.com.br/careers", location: "Sao Paulo, SP",
    country: "br", countryName: "Brazil",
    lat: -23.5505, lng: -46.6333,
    salary: "R$28,202/mo", salaryMin: 12201, salaryMax: 28202,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Develop strategic partnerships and expand market presence. Lead a team of sales representatives to exceed quarterly targets.",
    sector: "Sales", posted: "4 days ago", type: "Internship",
    contactEmail: "careers@magazineluiza.com",
    paywall: false,
  },

  {
    id: 136, title: "Brand Designer", company: "Totvs",
    companyUrl: "https://totvs.com.br/careers", location: "Salvador, BA",
    country: "br", countryName: "Brazil",
    lat: -12.9714, lng: -38.5124,
    salary: "R$28,837/mo", salaryMin: 7712, salaryMax: 28837,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Lead the visual identity and design system for the product. Ensure brand consistency across all touchpoints and mentor the design team.",
    sector: "Design", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@totvs.com",
    paywall: false,
  },

  {
    id: 137, title: "Medical Doctor", company: "Hapvida",
    companyUrl: "https://hapvida.com.br/careers", location: "Recife, PE",
    country: "br", countryName: "Brazil",
    lat: -8.0476, lng: -34.877,
    salary: "R$24,736/mo", salaryMin: 4773, salaryMax: 24736,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Conduct clinical trials and research studies to advance medical treatments. Analyze data and publish findings in peer-reviewed journals.",
    sector: "Healthcare", posted: "3 days ago", type: "Part-time",
    contactEmail: "careers@hapvida.com",
    paywall: true,
  },

  {
    id: 138, title: "Compensation Analyst", company: "Gupy",
    companyUrl: "https://gupy.io/careers", location: "Campinas, SP",
    country: "br", countryName: "Brazil",
    lat: -22.9099, lng: -47.0626,
    salary: "R$30,058/mo", salaryMin: 13052, salaryMax: 30058,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Develop and implement talent acquisition strategies to attract top candidates. Manage the full recruitment lifecycle and build employer branding.",
    sector: "HR", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@gupy.com",
    paywall: false,
  },

  {
    id: 139, title: "Mechanical Engineer", company: "Vale",
    companyUrl: "https://vale.com/careers", location: "Belo Horizonte, MG",
    country: "br", countryName: "Brazil",
    lat: -19.9167, lng: -43.9345,
    salary: "R$31,491/mo", salaryMin: 14513, salaryMax: 31491,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Develop innovative engineering solutions for complex technical challenges. Lead testing, validation, and quality assurance processes.",
    sector: "Engineering", posted: "3 days ago", type: "Contract",
    contactEmail: "careers@vale.com",
    paywall: false,
  },

  {
    id: 140, title: "Project Manager", company: "McKinsey Brasil",
    companyUrl: "https://mckinsey.com.br/careers", location: "Belo Horizonte, MG",
    country: "br", countryName: "Brazil",
    lat: -19.9167, lng: -43.9345,
    salary: "R$25,566/mo", salaryMin: 13769, salaryMax: 25566,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Own the product roadmap and prioritize features based on user research and business impact. Manage cross-functional teams and drive product launches.",
    sector: "Management", posted: "1 week ago", type: "Internship",
    contactEmail: "careers@mckinseybrasil.com",
    paywall: true,
  },

  {
    id: 141, title: "Marketing Manager", company: "Ambev",
    companyUrl: "https://ambev.com.br/careers", location: "Campinas, SP",
    country: "br", countryName: "Brazil",
    lat: -22.9099, lng: -47.0626,
    salary: "R$25,878/mo", salaryMin: 9163, salaryMax: 25878,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Create compelling content strategies that engage target audiences. Manage social media, email campaigns, and SEO optimization for maximum reach.",
    sector: "Marketing", posted: "3 days ago", type: "Part-time",
    contactEmail: "careers@ambev.com",
    paywall: false,
  },

  {
    id: 142, title: "Academic Researcher", company: "EBAC",
    companyUrl: "https://ebac.com.br/careers", location: "Florianopolis, SC",
    country: "br", countryName: "Brazil",
    lat: -27.5954, lng: -48.548,
    salary: "R$33,472/mo", salaryMin: 4391, salaryMax: 33472,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Develop innovative curriculum and learning materials for online and in-person programs. Leverage technology to create engaging educational experiences.",
    sector: "Education", posted: "5 days ago", type: "Internship",
    contactEmail: "careers@ebac.com",
    paywall: true,
  },

  {
    id: 143, title: "Corporate Lawyer", company: "Mattos Filho",
    companyUrl: "https://mattosfilho.com.br/careers", location: "Porto Alegre, RS",
    country: "br", countryName: "Brazil",
    lat: -30.0346, lng: -51.2177,
    salary: "R$25,947/mo", salaryMin: 13845, salaryMax: 25947,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Ensure organizational compliance with local and international regulations. Manage legal risk and advise on strategic business decisions.",
    sector: "Legal", posted: "4 days ago", type: "Remote",
    contactEmail: "careers@mattosfilho.com",
    paywall: false,
  },

  {
    id: 144, title: "Portfolio Manager", company: "Bradesco",
    companyUrl: "https://bradesco.com.br/careers", location: "Campinas, SP",
    country: "br", countryName: "Brazil",
    lat: -22.9099, lng: -47.0626,
    salary: "R$26,043/mo", salaryMin: 8655, salaryMax: 26043,
    salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Analyze financial statements and market trends to support investment decisions. Prepare detailed reports for C-level stakeholders and present quarterly performance reviews.",
    sector: "Finance", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@bradesco.com",
    paywall: true,
  }

];

// In-memory store for company-submitted jobs
const companyJobs: Job[] = [];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const country = searchParams.get("country");
  const type = searchParams.get("type");
  const sector = searchParams.get("sector");
  let filtered = [...jobs, ...companyJobs];
  if (country) {
    filtered = filtered.filter(j => j.country === country);
  }
  if (type && type !== "all") {
    filtered = filtered.filter(j => j.type.toLowerCase() === type.toLowerCase());
  }
  if (sector && sector !== "all") {
    filtered = filtered.filter(j => j.sector === sector);
  }
  return NextResponse.json(filtered);
}

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      companyName, companyUrl, companyEmail,
      title, location, country, countryName,
      salary, salaryMin, salaryMax, salaryCurrency, salaryPeriod,
      description, sector, type, remote
    } = body;

    if (!companyName || !title || !location || !country || !description || !sector || !type) {
      return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
    }

    const newJob: Job = {
      id: jobs.length + companyJobs.length + 1,
      title,
      company: companyName,
      companyUrl: companyUrl || "",
      location,
      country,
      countryName: countryName || country,
      lat: 0, lng: 0,
      salary: salary || "Negotiable",
      salaryMin: salaryMin || 0,
      salaryMax: salaryMax || 0,
      salaryCurrency: salaryCurrency || "USD",
      salaryPeriod: salaryPeriod || "month",
      description,
      sector,
      type: type === "remote" ? "Remote" : type,
      contactEmail: companyEmail || "",
      paywall: false,
    };

    companyJobs.push(newJob);
    return NextResponse.json({ success: true, job: newJob }, { status: 201 });
  } catch {
    return NextResponse.json({ error: "Invalid request" }, { status: 400 });
  }
}