import { NextResponse } from "next/server";

export interface Job {
  id: number; title: string; company: string; companyUrl: string;
  location: string; country: string; countryName: string;
  lat: number; lng: number;
  salary: string; salaryMin: number; salaryMax: number;
  salaryCurrency: string; salaryPeriod: string;
  description: string; sector: string; posted: string; type: string;
  contactEmail: string;
  paywall: boolean;
}

export const jobs: Job[] = [
  {
    id: 1, title: "Senior Software Engineer", company: "Tata Consultancy Services",
    companyUrl: "https://tataconsultancyservices.com/careers", location: "Mumbai, Maharashtra",
    country: "in", countryName: "India", lat: 19.076, lng: 72.8777,
    salary: "₹18,00,00 - 28,00,00/yr", salaryMin: 1800000, salaryMax: 2800000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Build enterprise-scale applications for global Fortune 500 clients. Work with microservices, cloud-native architecture on AWS/Azure. Lead a team of 6 engineers delivering critical banking and retail solutions.",
    sector: "Technology", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@tata.com",
    paywall: true,
  }
,
  {
    id: 2, title: "Data Scientist", company: "Infosys BPM",
    companyUrl: "https://infosysbpm.com/careers", location: "Bengaluru, Karnataka",
    country: "in", countryName: "India", lat: 12.9716, lng: 77.5946,
    salary: "₹15,00,00 - 22,00,00/yr", salaryMin: 1500000, salaryMax: 2200000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Analyze large datasets to build predictive models for banking and healthcare clients. Use Python, TensorFlow, and Spark. Present findings to C-level stakeholders across Asia-Pacific operations.",
    sector: "Data Science", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@infosys.com",
    paywall: false,
  }
,
  {
    id: 3, title: "Product Manager", company: "Flipkart",
    companyUrl: "https://flipkart.com/careers", location: "Bengaluru, Karnataka",
    country: "in", countryName: "India", lat: 12.9716, lng: 77.5946,
    salary: "₹22,00,00 - 35,00,00/yr", salaryMin: 2200000, salaryMax: 3500000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Own the product roadmap for Flipkart supply chain technology. Manage cross-functional teams of 15+ members. Drive user growth initiatives impacting 400M+ registered users across India.",
    sector: "Management", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@flipkart.com",
    paywall: true,
  }
,
  {
    id: 4, title: "UX Designer", company: "Wipro Design",
    companyUrl: "https://wiprodesign.com/careers", location: "Pune, Maharashtra",
    country: "in", countryName: "India", lat: 18.5204, lng: 73.8567,
    salary: "₹12,00,00 - 18,00,00/yr", salaryMin: 1200000, salaryMax: 1800000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Design intuitive user experiences for enterprise SaaS products used by millions. Conduct user research, create wireframes and prototypes, and collaborate with engineering teams to deliver pixel-perfect interfaces.",
    sector: "Design", posted: "4 days ago", type: "Full-time",
    contactEmail: "careers@wipro.com",
    paywall: false,
  }
,
  {
    id: 5, title: "Financial Analyst", company: "ICICI Bank",
    companyUrl: "https://icicibank.com/careers", location: "Mumbai, Maharashtra",
    country: "in", countryName: "India", lat: 19.076, lng: 72.8777,
    salary: "₹10,00,00 - 16,00,00/yr", salaryMin: 1000000, salaryMax: 1600000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Conduct financial modeling, risk assessment, and market research for retail banking products. Prepare investment presentations and support strategic planning for one of India largest private banks.",
    sector: "Finance", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@icici.com",
    paywall: true,
  }
,
  {
    id: 6, title: "Marketing Lead", company: "Zomato",
    companyUrl: "https://zomato.com/careers", location: "Gurugram, Haryana",
    country: "in", countryName: "India", lat: 28.4595, lng: 77.0266,
    salary: "₹14,00,00 - 22,00,00/yr", salaryMin: 1400000, salaryMax: 2200000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Lead digital marketing campaigns across India food delivery market. Manage a team of 12 specialists, oversee annual budget of 50 crore, and develop growth strategies for tier-2 city expansion.",
    sector: "Marketing", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@zomato.com",
    paywall: false,
  }
,
  {
    id: 7, title: "DevOps Engineer", company: "Razorpay",
    companyUrl: "https://razorpay.com/careers", location: "Bengaluru, Karnataka",
    country: "in", countryName: "India", lat: 12.9716, lng: 77.5946,
    salary: "₹16,00,00 - 24,00,00/yr", salaryMin: 1600000, salaryMax: 2400000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Manage CI/CD pipelines and cloud infrastructure on AWS and GCP. Automate deployment processes for payment systems handling 10M+ daily transactions with 99.99% uptime.",
    sector: "Technology", posted: "1 week ago", type: "Remote",
    contactEmail: "careers@razorpay.com",
    paywall: true,
  }
,
  {
    id: 8, title: "Sales Manager", company: "Reliance Retail",
    companyUrl: "https://relianceretail.com/careers", location: "Mumbai, Maharashtra",
    country: "in", countryName: "India", lat: 19.076, lng: 72.8777,
    salary: "₹11,00,00 - 18,00,00/yr", salaryMin: 1100000, salaryMax: 1800000, salaryCurrency: "INR", salaryPeriod: "year",
    description: "Drive B2B enterprise sales for India largest retail chain. Manage a pipeline of 200 crore+, negotiate contracts with key partners, and exceed quarterly revenue targets across western India.",
    sector: "Sales", posted: "2 weeks ago", type: "Hybrid",
    contactEmail: "careers@reliance.com",
    paywall: false,
  }
,
  {
    id: 25, title: "Data Scientist", company: "DataPulse Analytics",
    companyUrl: "https://datapulseanalytics.com/careers", location: "Sao Paulo, SP",
    country: "br", countryName: "Brazil", lat: -23.5505, lng: -46.6333,
    salary: "R$ 18,000 - 25,000/mo", salaryMin: 18000, salaryMax: 25000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Build predictive models using Python, TensorFlow and Spark. Present findings to C-level stakeholders.",
    sector: "Data Science", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@datapulse.com",
    paywall: true,
  }
,
  {
    id: 26, title: "Backend Developer", company: "NexaSoft Technologies",
    companyUrl: "https://nexasofttechnologies.com/careers", location: "Rio de Janeiro, RJ",
    country: "br", countryName: "Brazil", lat: -22.9068, lng: -43.1729,
    salary: "R$ 14,000 - 20,000/mo", salaryMin: 14000, salaryMax: 20000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Develop robust RESTful APIs and microservices using Node.js and PostgreSQL. Implement authentication systems, optimize database queries, and mentor junior developers.",
    sector: "Technology", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@nexasoft.com",
    paywall: false,
  }
,
  {
    id: 27, title: "Product Manager", company: "Nubank",
    companyUrl: "https://nubank.com/careers", location: "Sao Paulo, SP",
    country: "br", countryName: "Brazil", lat: -23.5505, lng: -46.6333,
    salary: "R$ 22,000 - 35,000/mo", salaryMin: 22000, salaryMax: 35000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Own the product roadmap for digital banking features serving 80M+ customers. Manage cross-functional teams and drive innovation in Latin America largest digital bank.",
    sector: "Management", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@nubank.com",
    paywall: true,
  }
,
  {
    id: 28, title: "UX Designer", company: "Concrete Solucoes",
    companyUrl: "https://concretesolucoes.com/careers", location: "Sao Paulo, SP",
    country: "br", countryName: "Brazil", lat: -23.5505, lng: -46.6333,
    salary: "R$ 12,000 - 18,000/mo", salaryMin: 12000, salaryMax: 18000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Design user experiences for enterprise software and mobile apps. Conduct usability testing, create design systems, and collaborate with development teams on agile projects.",
    sector: "Design", posted: "4 days ago", type: "Full-time",
    contactEmail: "careers@concrete.com",
    paywall: false,
  }
,
  {
    id: 29, title: "Marketing Analyst", company: "Ambev",
    companyUrl: "https://ambev.com/careers", location: "Sao Paulo, SP",
    country: "br", countryName: "Brazil", lat: -23.5505, lng: -46.6333,
    salary: "R$ 8,000 - 13,000/mo", salaryMin: 8000, salaryMax: 13000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Develop and execute marketing campaigns for Brazil largest beverage company. Analyze market trends, manage social media strategy, and support brand positioning across national markets.",
    sector: "Marketing", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@ambev.com",
    paywall: true,
  }
,
  {
    id: 30, title: "Financial Analyst", company: "Itau Unibanco",
    companyUrl: "https://itauunibanco.com/careers", location: "Sao Paulo, SP",
    country: "br", countryName: "Brazil", lat: -23.5505, lng: -46.6333,
    salary: "R$ 10,000 - 16,000/mo", salaryMin: 10000, salaryMax: 16000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Conduct financial analysis and risk assessment for corporate banking division. Prepare credit reports, support loan structuring, and assist in portfolio management for top-tier clients.",
    sector: "Finance", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@itau.com",
    paywall: false,
  }
,
  {
    id: 31, title: "Sales Manager", company: "Magazine Luiza",
    companyUrl: "https://magazineluiza.com/careers", location: "Franca, SP",
    country: "br", countryName: "Brazil", lat: -20.5386, lng: -47.4027,
    salary: "R$ 9,000 - 15,000/mo", salaryMin: 9000, salaryMax: 15000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Lead B2B sales operations for one of Brazil largest e-commerce retailers. Manage key accounts, negotiate enterprise contracts, and drive revenue growth in the wholesale channel.",
    sector: "Sales", posted: "1 week ago", type: "Remote",
    contactEmail: "careers@magazine.com",
    paywall: true,
  }
,
  {
    id: 32, title: "HR Specialist", company: "WEG S.A.",
    companyUrl: "https://wegsa.com/careers", location: "Jaragua do Sul, SC",
    country: "br", countryName: "Brazil", lat: -26.4834, lng: -49.0665,
    salary: "R$ 7,000 - 11,000/mo", salaryMin: 7000, salaryMax: 11000, salaryCurrency: "BRL", salaryPeriod: "month",
    description: "Manage recruitment and talent development programs for a global manufacturing company. Lead employer branding initiatives and implement performance management systems across 5 facilities.",
    sector: "HR", posted: "2 weeks ago", type: "Hybrid",
    contactEmail: "careers@weg.com",
    paywall: false,
  }
,
  {
    id: 145, title: "Fintech Software Developer", company: "Flutterwave",
    companyUrl: "https://flutterwave.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 12M - 20M/yr", salaryMin: 12000000, salaryMax: 20000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Build payment processing infrastructure serving 30+ African countries. Work with Java, Go, and distributed systems. Handle millions of transactions daily.",
    sector: "Finance", posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@flutterwave.com",
    paywall: true,
  }
,
  {
    id: 146, title: "Product Manager", company: "Jumia",
    companyUrl: "https://jumia.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 10M - 16M/yr", salaryMin: 10000000, salaryMax: 16000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Own the product roadmap for Africa largest e-commerce platform. Manage cross-functional teams and drive features serving 30M+ monthly active users.",
    sector: "Management", posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@jumia.com",
    paywall: false,
  }
,
  {
    id: 147, title: "Data Analyst", company: "Interswitch",
    companyUrl: "https://interswitch.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 8M - 14M/yr", salaryMin: 8000000, salaryMax: 14000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Analyze transaction data for Africa largest payment processing company. Build dashboards, develop fraud detection models, and optimize payment flows.",
    sector: "Data Science", posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@interswitch.com",
    paywall: true,
  }
,
  {
    id: 148, title: "Software Engineer", company: "Andela",
    companyUrl: "https://andela.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 10M - 18M/yr", salaryMin: 10000000, salaryMax: 18000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Build talent marketplace platform connecting African developers with global companies. Work with React, Node.js, and AI-powered matching algorithms.",
    sector: "Technology", posted: "4 days ago", type: "Full-time",
    contactEmail: "careers@andela.com",
    paywall: false,
  }
,
  {
    id: 149, title: "Marketing Manager", company: "Dangote Group",
    companyUrl: "https://dangotegroup.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 9M - 15M/yr", salaryMin: 9000000, salaryMax: 15000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Lead marketing for Africa largest conglomerate. Manage brand campaigns across FMCG, cement, and sugar divisions. Oversee multi-million dollar budgets.",
    sector: "Marketing", posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@dangote.com",
    paywall: true,
  }
,
  {
    id: 150, title: "Financial Analyst", company: "Access Bank",
    companyUrl: "https://accessbank.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 7M - 12M/yr", salaryMin: 7000000, salaryMax: 12000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Conduct financial analysis for Africa largest bank by customer base. Prepare credit assessments, support corporate lending decisions.",
    sector: "Finance", posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@access.com",
    paywall: false,
  }
,
  {
    id: 151, title: "UX Designer", company: "Paystack",
    companyUrl: "https://paystack.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 8M - 13M/yr", salaryMin: 8000000, salaryMax: 13000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Design payment and merchant dashboard experiences serving 60,000+ businesses. Create intuitive interfaces for diverse African markets with varying tech literacy.",
    sector: "Design", posted: "1 week ago", type: "Remote",
    contactEmail: "careers@paystack.com",
    paywall: true,
  }
,
  {
    id: 152, title: "Sales Director", company: "MTN Nigeria",
    companyUrl: "https://mtnnigeria.com/careers", location: "Lagos",
    country: "ng", countryName: "Nigeria", lat: 6.5244, lng: 3.3792,
    salary: "NGN 11M - 18M/yr", salaryMin: 11000000, salaryMax: 18000000, salaryCurrency: "NGN", salaryPeriod: "year",
    description: "Lead enterprise sales for Nigeria largest telecom. Manage key accounts, drive B2B revenue growth, and expand market share across Nigerian states.",
    sector: "Sales", posted: "2 weeks ago", type: "Hybrid",
    contactEmail: "careers@mtn.com",
    paywall: false,
  }
,
  {
    id: 201, title: "Senior Software Engineer", company: "Standard Bank",
    companyUrl: "https://standardbank.com",
    location: "Johannesburg, South Africa", country: "za", countryName: "South Africa",
    lat: -26.2041, lng: 28.0473,
    salary: "R350K - R553K/year",
    salaryMin: 350000, salaryMax: 553333,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@standardbank.com",
    paywall: true,
  },
  {
    id: 202, title: "Data Analyst", company: "MTN Group",
    companyUrl: "https://mtngroup.com",
    location: "Cape Town, South Africa", country: "za", countryName: "South Africa",
    lat: -33.9249, lng: 18.4241,
    salary: "R400K - R604K/year",
    salaryMin: 400833, salaryMax: 604166,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@mtngroup.com",
    paywall: false,
  },
  {
    id: 203, title: "Financial Accountant", company: "Sasol",
    companyUrl: "https://sasol.com",
    location: "Durban, South Africa", country: "za", countryName: "South Africa",
    lat: -29.8587, lng: 31.0218,
    salary: "R451K - R654K/year",
    salaryMin: 451666, salaryMax: 654999,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@sasol.com",
    paywall: true,
  },
  {
    id: 204, title: "Marketing Manager", company: "Discovery Health",
    companyUrl: "https://discoveryhealth.com",
    location: "Pretoria, South Africa", country: "za", countryName: "South Africa",
    lat: -25.7479, lng: 28.2293,
    salary: "R502K - R705K/year",
    salaryMin: 502500, salaryMax: 705833,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@discoveryhealth.com",
    paywall: false,
  },
  {
    id: 205, title: "UX/UI Designer", company: "Shoprite",
    companyUrl: "https://shoprite.com",
    location: "Sandton, South Africa", country: "za", countryName: "South Africa",
    lat: -26.1076, lng: 28.0546,
    salary: "R553K - R756K/year",
    salaryMin: 553333, salaryMax: 756666,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@shoprite.com",
    paywall: true,
  },
  {
    id: 206, title: "Sales Executive", company: "Naspers",
    companyUrl: "https://naspers.com",
    location: "Johannesburg, South Africa", country: "za", countryName: "South Africa",
    lat: -26.2041, lng: 28.0473,
    salary: "R604K - R807K/year",
    salaryMin: 604166, salaryMax: 807499,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@naspers.com",
    paywall: false,
  },
  {
    id: 207, title: "Project Manager", company: "Anglo American",
    companyUrl: "https://angloamerican.com",
    location: "Cape Town, South Africa", country: "za", countryName: "South Africa",
    lat: -33.9249, lng: 18.4241,
    salary: "R655K - R858K/year",
    salaryMin: 655000, salaryMax: 858333,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@angloamerican.com",
    paywall: true,
  },
  {
    id: 208, title: "Registered Nurse", company: "Old Mutual",
    companyUrl: "https://oldmutual.com",
    location: "Durban, South Africa", country: "za", countryName: "South Africa",
    lat: -29.8587, lng: 31.0218,
    salary: "R705K - R909K/year",
    salaryMin: 705833, salaryMax: 909166,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@oldmutual.com",
    paywall: false,
  },
  {
    id: 209, title: "Civil Engineer", company: "Standard Bank",
    companyUrl: "https://standardbank.com",
    location: "Pretoria, South Africa", country: "za", countryName: "South Africa",
    lat: -25.7479, lng: 28.2293,
    salary: "R756K - R959K/year",
    salaryMin: 756666, salaryMax: 959999,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@standardbank.com",
    paywall: true,
  },
  {
    id: 210, title: "Remote Customer Support Specialist", company: "MTN Group",
    companyUrl: "https://mtngroup.com",
    location: "Sandton, South Africa", country: "za", countryName: "South Africa",
    lat: -26.1076, lng: 28.0546,
    salary: "R807K - R1010K/year",
    salaryMin: 807500, salaryMax: 1010833,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@mtngroup.com",
    paywall: false,
  },
  {
    id: 211, title: "DevOps Engineer", company: "Sasol",
    companyUrl: "https://sasol.com",
    location: "Johannesburg, South Africa", country: "za", countryName: "South Africa",
    lat: -26.2041, lng: 28.0473,
    salary: "R858K - R1061K/year",
    salaryMin: 858333, salaryMax: 1061666,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@sasol.com",
    paywall: true,
  },
  {
    id: 212, title: "Business Development Manager", company: "Discovery Health",
    companyUrl: "https://discoveryhealth.com",
    location: "Cape Town, South Africa", country: "za", countryName: "South Africa",
    lat: -33.9249, lng: 18.4241,
    salary: "R909K - R1112K/year",
    salaryMin: 909166, salaryMax: 1112499,
    salaryCurrency: "ZAR", salaryPeriod: "year",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@discoveryhealth.com",
    paywall: false,
  },
  {
    id: 213, title: "Senior Software Engineer", company: "Safaricom",
    companyUrl: "https://safaricom.com",
    location: "Nairobi, Kenya", country: "ke", countryName: "Kenya",
    lat: -1.2921, lng: 36.8219,
    salary: "KSh60K - KSh160K/month",
    salaryMin: 60000, salaryMax: 160000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@safaricom.com",
    paywall: true,
  },
  {
    id: 214, title: "Data Analyst", company: "Equity Bank",
    companyUrl: "https://equitybank.com",
    location: "Mombasa, Kenya", country: "ke", countryName: "Kenya",
    lat: -4.0435, lng: 39.6682,
    salary: "KSh85K - KSh185K/month",
    salaryMin: 85000, salaryMax: 185000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@equitybank.com",
    paywall: false,
  },
  {
    id: 215, title: "Financial Accountant", company: "Kenya Commercial Bank",
    companyUrl: "https://kenyacommercialbank.com",
    location: "Kisumu, Kenya", country: "ke", countryName: "Kenya",
    lat: -0.1022, lng: 34.7617,
    salary: "KSh110K - KSh210K/month",
    salaryMin: 110000, salaryMax: 210000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@kenyacommercialbank.com",
    paywall: true,
  },
  {
    id: 216, title: "Marketing Manager", company: "East African Breweries",
    companyUrl: "https://eastafricanbreweries.com",
    location: "Nakuru, Kenya", country: "ke", countryName: "Kenya",
    lat: -0.3031, lng: 36.08,
    salary: "KSh135K - KSh235K/month",
    salaryMin: 135000, salaryMax: 235000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@eastafricanbreweries.com",
    paywall: false,
  },
  {
    id: 217, title: "UX/UI Designer", company: "KCB Group",
    companyUrl: "https://kcbgroup.com",
    location: "Eldoret, Kenya", country: "ke", countryName: "Kenya",
    lat: 0.5143, lng: 35.2698,
    salary: "KSh160K - KSh260K/month",
    salaryMin: 160000, salaryMax: 260000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@kcbgroup.com",
    paywall: true,
  },
  {
    id: 218, title: "Sales Executive", company: "NCBA Bank",
    companyUrl: "https://ncbabank.com",
    location: "Nairobi, Kenya", country: "ke", countryName: "Kenya",
    lat: -1.2921, lng: 36.8219,
    salary: "KSh185K - KSh285K/month",
    salaryMin: 185000, salaryMax: 285000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@ncbabank.com",
    paywall: false,
  },
  {
    id: 219, title: "Project Manager", company: "Bidco Africa",
    companyUrl: "https://bidcoafrica.com",
    location: "Mombasa, Kenya", country: "ke", countryName: "Kenya",
    lat: -4.0435, lng: 39.6682,
    salary: "KSh210K - KSh310K/month",
    salaryMin: 210000, salaryMax: 310000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@bidcoafrica.com",
    paywall: true,
  },
  {
    id: 220, title: "Registered Nurse", company: "Britam",
    companyUrl: "https://britam.com",
    location: "Kisumu, Kenya", country: "ke", countryName: "Kenya",
    lat: -0.1022, lng: 34.7617,
    salary: "KSh235K - KSh335K/month",
    salaryMin: 235000, salaryMax: 335000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@britam.com",
    paywall: false,
  },
  {
    id: 221, title: "Civil Engineer", company: "Safaricom",
    companyUrl: "https://safaricom.com",
    location: "Nakuru, Kenya", country: "ke", countryName: "Kenya",
    lat: -0.3031, lng: 36.08,
    salary: "KSh260K - KSh360K/month",
    salaryMin: 260000, salaryMax: 360000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@safaricom.com",
    paywall: true,
  },
  {
    id: 222, title: "Remote Customer Support Specialist", company: "Equity Bank",
    companyUrl: "https://equitybank.com",
    location: "Eldoret, Kenya", country: "ke", countryName: "Kenya",
    lat: 0.5143, lng: 35.2698,
    salary: "KSh285K - KSh385K/month",
    salaryMin: 285000, salaryMax: 385000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@equitybank.com",
    paywall: false,
  },
  {
    id: 223, title: "DevOps Engineer", company: "Kenya Commercial Bank",
    companyUrl: "https://kenyacommercialbank.com",
    location: "Nairobi, Kenya", country: "ke", countryName: "Kenya",
    lat: -1.2921, lng: 36.8219,
    salary: "KSh310K - KSh410K/month",
    salaryMin: 310000, salaryMax: 410000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@kenyacommercialbank.com",
    paywall: true,
  },
  {
    id: 224, title: "Business Development Manager", company: "East African Breweries",
    companyUrl: "https://eastafricanbreweries.com",
    location: "Mombasa, Kenya", country: "ke", countryName: "Kenya",
    lat: -4.0435, lng: 39.6682,
    salary: "KSh335K - KSh435K/month",
    salaryMin: 335000, salaryMax: 435000,
    salaryCurrency: "KES", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@eastafricanbreweries.com",
    paywall: false,
  },
  {
    id: 225, title: "Senior Software Engineer", company: "Orascom Construction",
    companyUrl: "https://orascomconstruction.com",
    location: "Cairo, Egypt", country: "eg", countryName: "Egypt",
    lat: 30.0444, lng: 31.2357,
    salary: "E£8K - E£20K/month",
    salaryMin: 8000, salaryMax: 20333,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@orascomconstruction.com",
    paywall: true,
  },
  {
    id: 226, title: "Data Analyst", company: "Vodafone Egypt",
    companyUrl: "https://vodafoneegypt.com",
    location: "Alexandria, Egypt", country: "eg", countryName: "Egypt",
    lat: 31.2001, lng: 29.9187,
    salary: "E£11K - E£23K/month",
    salaryMin: 11083, salaryMax: 23416,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@vodafoneegypt.com",
    paywall: false,
  },
  {
    id: 227, title: "Financial Accountant", company: "El Sewedy Electric",
    companyUrl: "https://elsewedyelectric.com",
    location: "Giza, Egypt", country: "eg", countryName: "Egypt",
    lat: 29.9765, lng: 31.1313,
    salary: "E£14K - E£26K/month",
    salaryMin: 14166, salaryMax: 26499,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@elsewedyelectric.com",
    paywall: true,
  },
  {
    id: 228, title: "Marketing Manager", company: "Banque Misr",
    companyUrl: "https://banquemisr.com",
    location: "Sharm El Sheikh, Egypt", country: "eg", countryName: "Egypt",
    lat: 27.9158, lng: 34.33,
    salary: "E£17K - E£29K/month",
    salaryMin: 17250, salaryMax: 29583,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@banquemisr.com",
    paywall: false,
  },
  {
    id: 229, title: "UX/UI Designer", company: "QNB AlaAhli",
    companyUrl: "https://qnbalaahli.com",
    location: "Luxor, Egypt", country: "eg", countryName: "Egypt",
    lat: 25.6872, lng: 32.6396,
    salary: "E£20K - E£32K/month",
    salaryMin: 20333, salaryMax: 32666,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@qnbalaahli.com",
    paywall: true,
  },
  {
    id: 230, title: "Sales Executive", company: "SODIC",
    companyUrl: "https://sodic.com",
    location: "Cairo, Egypt", country: "eg", countryName: "Egypt",
    lat: 30.0444, lng: 31.2357,
    salary: "E£23K - E£35K/month",
    salaryMin: 23416, salaryMax: 35749,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@sodic.com",
    paywall: false,
  },
  {
    id: 231, title: "Project Manager", company: "Talaat Moustafa Group",
    companyUrl: "https://talaatmoustafagroup.com",
    location: "Alexandria, Egypt", country: "eg", countryName: "Egypt",
    lat: 31.2001, lng: 29.9187,
    salary: "E£26K - E£38K/month",
    salaryMin: 26500, salaryMax: 38833,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@talaatmoustafagroup.com",
    paywall: true,
  },
  {
    id: 232, title: "Registered Nurse", company: "Cairo Bank",
    companyUrl: "https://cairobank.com",
    location: "Giza, Egypt", country: "eg", countryName: "Egypt",
    lat: 29.9765, lng: 31.1313,
    salary: "E£29K - E£41K/month",
    salaryMin: 29583, salaryMax: 41916,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@cairobank.com",
    paywall: false,
  },
  {
    id: 233, title: "Civil Engineer", company: "Orascom Construction",
    companyUrl: "https://orascomconstruction.com",
    location: "Sharm El Sheikh, Egypt", country: "eg", countryName: "Egypt",
    lat: 27.9158, lng: 34.33,
    salary: "E£32K - E£44K/month",
    salaryMin: 32666, salaryMax: 44999,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@orascomconstruction.com",
    paywall: true,
  },
  {
    id: 234, title: "Remote Customer Support Specialist", company: "Vodafone Egypt",
    companyUrl: "https://vodafoneegypt.com",
    location: "Luxor, Egypt", country: "eg", countryName: "Egypt",
    lat: 25.6872, lng: 32.6396,
    salary: "E£35K - E£48K/month",
    salaryMin: 35750, salaryMax: 48083,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@vodafoneegypt.com",
    paywall: false,
  },
  {
    id: 235, title: "DevOps Engineer", company: "El Sewedy Electric",
    companyUrl: "https://elsewedyelectric.com",
    location: "Cairo, Egypt", country: "eg", countryName: "Egypt",
    lat: 30.0444, lng: 31.2357,
    salary: "E£38K - E£51K/month",
    salaryMin: 38833, salaryMax: 51166,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@elsewedyelectric.com",
    paywall: true,
  },
  {
    id: 236, title: "Business Development Manager", company: "Banque Misr",
    companyUrl: "https://banquemisr.com",
    location: "Alexandria, Egypt", country: "eg", countryName: "Egypt",
    lat: 31.2001, lng: 29.9187,
    salary: "E£41K - E£54K/month",
    salaryMin: 41916, salaryMax: 54249,
    salaryCurrency: "EGP", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@banquemisr.com",
    paywall: false,
  },
  {
    id: 237, title: "Senior Software Engineer", company: "Ayala Corporation",
    companyUrl: "https://ayalacorporation.com",
    location: "Manila, Philippines", country: "ph", countryName: "Philippines",
    lat: 14.5995, lng: 120.9842,
    salary: "₱25K - ₱45K/month",
    salaryMin: 25000, salaryMax: 45000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@ayalacorporation.com",
    paywall: true,
  },
  {
    id: 238, title: "Data Analyst", company: "SM Investments",
    companyUrl: "https://sminvestments.com",
    location: "Cebu City, Philippines", country: "ph", countryName: "Philippines",
    lat: 10.3157, lng: 123.8854,
    salary: "₱30K - ₱50K/month",
    salaryMin: 30000, salaryMax: 50000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@sminvestments.com",
    paywall: false,
  },
  {
    id: 239, title: "Financial Accountant", company: "BDO Unibank",
    companyUrl: "https://bdounibank.com",
    location: "Davao City, Philippines", country: "ph", countryName: "Philippines",
    lat: 7.1907, lng: 125.4553,
    salary: "₱35K - ₱55K/month",
    salaryMin: 35000, salaryMax: 55000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@bdounibank.com",
    paywall: true,
  },
  {
    id: 240, title: "Marketing Manager", company: "PLDT",
    companyUrl: "https://pldt.com",
    location: "Quezon City, Philippines", country: "ph", countryName: "Philippines",
    lat: 14.676, lng: 121.0437,
    salary: "₱40K - ₱60K/month",
    salaryMin: 40000, salaryMax: 60000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@pldt.com",
    paywall: false,
  },
  {
    id: 241, title: "UX/UI Designer", company: "Globe Telecom",
    companyUrl: "https://globetelecom.com",
    location: "Makati, Philippines", country: "ph", countryName: "Philippines",
    lat: 14.5547, lng: 121.0244,
    salary: "₱45K - ₱65K/month",
    salaryMin: 45000, salaryMax: 65000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@globetelecom.com",
    paywall: true,
  },
  {
    id: 242, title: "Sales Executive", company: "Jollibee Foods",
    companyUrl: "https://jollibeefoods.com",
    location: "Manila, Philippines", country: "ph", countryName: "Philippines",
    lat: 14.5995, lng: 120.9842,
    salary: "₱50K - ₱70K/month",
    salaryMin: 50000, salaryMax: 70000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@jollibeefoods.com",
    paywall: false,
  },
  {
    id: 243, title: "Project Manager", company: "San Miguel Corp",
    companyUrl: "https://sanmiguelcorp.com",
    location: "Cebu City, Philippines", country: "ph", countryName: "Philippines",
    lat: 10.3157, lng: 123.8854,
    salary: "₱55K - ₱75K/month",
    salaryMin: 55000, salaryMax: 75000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@sanmiguelcorp.com",
    paywall: true,
  },
  {
    id: 244, title: "Registered Nurse", company: "Metro Bank",
    companyUrl: "https://metrobank.com",
    location: "Davao City, Philippines", country: "ph", countryName: "Philippines",
    lat: 7.1907, lng: 125.4553,
    salary: "₱60K - ₱80K/month",
    salaryMin: 60000, salaryMax: 80000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@metrobank.com",
    paywall: false,
  },
  {
    id: 245, title: "Civil Engineer", company: "Ayala Corporation",
    companyUrl: "https://ayalacorporation.com",
    location: "Quezon City, Philippines", country: "ph", countryName: "Philippines",
    lat: 14.676, lng: 121.0437,
    salary: "₱65K - ₱85K/month",
    salaryMin: 65000, salaryMax: 85000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@ayalacorporation.com",
    paywall: true,
  },
  {
    id: 246, title: "Remote Customer Support Specialist", company: "SM Investments",
    companyUrl: "https://sminvestments.com",
    location: "Makati, Philippines", country: "ph", countryName: "Philippines",
    lat: 14.5547, lng: 121.0244,
    salary: "₱70K - ₱90K/month",
    salaryMin: 70000, salaryMax: 90000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@sminvestments.com",
    paywall: false,
  },
  {
    id: 247, title: "DevOps Engineer", company: "BDO Unibank",
    companyUrl: "https://bdounibank.com",
    location: "Manila, Philippines", country: "ph", countryName: "Philippines",
    lat: 14.5995, lng: 120.9842,
    salary: "₱75K - ₱95K/month",
    salaryMin: 75000, salaryMax: 95000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@bdounibank.com",
    paywall: true,
  },
  {
    id: 248, title: "Business Development Manager", company: "PLDT",
    companyUrl: "https://pldt.com",
    location: "Cebu City, Philippines", country: "ph", countryName: "Philippines",
    lat: 10.3157, lng: 123.8854,
    salary: "₱80K - ₱100K/month",
    salaryMin: 80000, salaryMax: 100000,
    salaryCurrency: "PHP", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@pldt.com",
    paywall: false,
  },
  {
    id: 249, title: "Senior Software Engineer", company: "MTN Ghana",
    companyUrl: "https://mtnghana.com",
    location: "Accra, Ghana", country: "gh", countryName: "Ghana",
    lat: 5.6037, lng: -0.187,
    salary: "GH¢3K - GH¢7K/month",
    salaryMin: 3000, salaryMax: 7000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@mtnghana.com",
    paywall: true,
  },
  {
    id: 250, title: "Data Analyst", company: "GCB Bank",
    companyUrl: "https://gcbbank.com",
    location: "Kumasi, Ghana", country: "gh", countryName: "Ghana",
    lat: 6.6884, lng: -1.6244,
    salary: "GH¢4K - GH¢8K/month",
    salaryMin: 4000, salaryMax: 8000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@gcbbank.com",
    paywall: false,
  },
  {
    id: 251, title: "Financial Accountant", company: "Newmont Ghana",
    companyUrl: "https://newmontghana.com",
    location: "Tamale, Ghana", country: "gh", countryName: "Ghana",
    lat: 9.4034, lng: -0.8393,
    salary: "GH¢5K - GH¢9K/month",
    salaryMin: 5000, salaryMax: 9000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@newmontghana.com",
    paywall: true,
  },
  {
    id: 252, title: "Marketing Manager", company: "TotalEnergies Ghana",
    companyUrl: "https://totalenergiesghana.com",
    location: "Takoradi, Ghana", country: "gh", countryName: "Ghana",
    lat: 4.8983, lng: -1.7607,
    salary: "GH¢6K - GH¢10K/month",
    salaryMin: 6000, salaryMax: 10000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@totalenergiesghana.com",
    paywall: false,
  },
  {
    id: 253, title: "UX/UI Designer", company: "Unilever Ghana",
    companyUrl: "https://unileverghana.com",
    location: "Tema, Ghana", country: "gh", countryName: "Ghana",
    lat: 5.6692, lng: -0.0166,
    salary: "GH¢7K - GH¢11K/month",
    salaryMin: 7000, salaryMax: 11000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@unileverghana.com",
    paywall: true,
  },
  {
    id: 254, title: "Sales Executive", company: "Ecobank Ghana",
    companyUrl: "https://ecobankghana.com",
    location: "Accra, Ghana", country: "gh", countryName: "Ghana",
    lat: 5.6037, lng: -0.187,
    salary: "GH¢8K - GH¢12K/month",
    salaryMin: 8000, salaryMax: 12000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@ecobankghana.com",
    paywall: false,
  },
  {
    id: 255, title: "Project Manager", company: "Fan Milk Ltd",
    companyUrl: "https://fanmilkltd.com",
    location: "Kumasi, Ghana", country: "gh", countryName: "Ghana",
    lat: 6.6884, lng: -1.6244,
    salary: "GH¢9K - GH¢13K/month",
    salaryMin: 9000, salaryMax: 13000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@fanmilkltd.com",
    paywall: true,
  },
  {
    id: 256, title: "Registered Nurse", company: "Guinness Ghana",
    companyUrl: "https://guinnessghana.com",
    location: "Tamale, Ghana", country: "gh", countryName: "Ghana",
    lat: 9.4034, lng: -0.8393,
    salary: "GH¢10K - GH¢14K/month",
    salaryMin: 10000, salaryMax: 14000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@guinnessghana.com",
    paywall: false,
  },
  {
    id: 257, title: "Civil Engineer", company: "MTN Ghana",
    companyUrl: "https://mtnghana.com",
    location: "Takoradi, Ghana", country: "gh", countryName: "Ghana",
    lat: 4.8983, lng: -1.7607,
    salary: "GH¢11K - GH¢15K/month",
    salaryMin: 11000, salaryMax: 15000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@mtnghana.com",
    paywall: true,
  },
  {
    id: 258, title: "Remote Customer Support Specialist", company: "GCB Bank",
    companyUrl: "https://gcbbank.com",
    location: "Tema, Ghana", country: "gh", countryName: "Ghana",
    lat: 5.6692, lng: -0.0166,
    salary: "GH¢12K - GH¢16K/month",
    salaryMin: 12000, salaryMax: 16000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@gcbbank.com",
    paywall: false,
  },
  {
    id: 259, title: "DevOps Engineer", company: "Newmont Ghana",
    companyUrl: "https://newmontghana.com",
    location: "Accra, Ghana", country: "gh", countryName: "Ghana",
    lat: 5.6037, lng: -0.187,
    salary: "GH¢13K - GH¢17K/month",
    salaryMin: 13000, salaryMax: 17000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@newmontghana.com",
    paywall: true,
  },
  {
    id: 260, title: "Business Development Manager", company: "TotalEnergies Ghana",
    companyUrl: "https://totalenergiesghana.com",
    location: "Kumasi, Ghana", country: "gh", countryName: "Ghana",
    lat: 6.6884, lng: -1.6244,
    salary: "GH¢14K - GH¢18K/month",
    salaryMin: 14000, salaryMax: 18000,
    salaryCurrency: "GHS", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@totalenergiesghana.com",
    paywall: false,
  },
  {
    id: 261, title: "Senior Software Engineer", company: "Engro Corporation",
    companyUrl: "https://engrocorporation.com",
    location: "Karachi, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 24.8607, lng: 67.0011,
    salary: "Rs50K - Rs150K/month",
    salaryMin: 50000, salaryMax: 150000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@engrocorporation.com",
    paywall: true,
  },
  {
    id: 262, title: "Data Analyst", company: "Habib Bank",
    companyUrl: "https://habibbank.com",
    location: "Lahore, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 31.5204, lng: 74.3587,
    salary: "Rs75K - Rs175K/month",
    salaryMin: 75000, salaryMax: 175000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@habibbank.com",
    paywall: false,
  },
  {
    id: 263, title: "Financial Accountant", company: "Lucky Cement",
    companyUrl: "https://luckycement.com",
    location: "Islamabad, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 33.6844, lng: 73.0479,
    salary: "Rs100K - Rs200K/month",
    salaryMin: 100000, salaryMax: 200000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@luckycement.com",
    paywall: true,
  },
  {
    id: 264, title: "Marketing Manager", company: "PTCL",
    companyUrl: "https://ptcl.com",
    location: "Rawalpindi, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 33.5651, lng: 73.0169,
    salary: "Rs125K - Rs225K/month",
    salaryMin: 125000, salaryMax: 225000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@ptcl.com",
    paywall: false,
  },
  {
    id: 265, title: "UX/UI Designer", company: "Systems Limited",
    companyUrl: "https://systemslimited.com",
    location: "Faisalabad, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 31.4504, lng: 73.135,
    salary: "Rs150K - Rs250K/month",
    salaryMin: 150000, salaryMax: 250000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@systemslimited.com",
    paywall: true,
  },
  {
    id: 266, title: "Sales Executive", company: "Nestle Pakistan",
    companyUrl: "https://nestlepakistan.com",
    location: "Karachi, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 24.8607, lng: 67.0011,
    salary: "Rs175K - Rs275K/month",
    salaryMin: 175000, salaryMax: 275000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@nestlepakistan.com",
    paywall: false,
  },
  {
    id: 267, title: "Project Manager", company: "Unilever Pakistan",
    companyUrl: "https://unileverpakistan.com",
    location: "Lahore, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 31.5204, lng: 74.3587,
    salary: "Rs200K - Rs300K/month",
    salaryMin: 200000, salaryMax: 300000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@unileverpakistan.com",
    paywall: true,
  },
  {
    id: 268, title: "Registered Nurse", company: "Bank Alfalah",
    companyUrl: "https://bankalfalah.com",
    location: "Islamabad, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 33.6844, lng: 73.0479,
    salary: "Rs225K - Rs325K/month",
    salaryMin: 225000, salaryMax: 325000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@bankalfalah.com",
    paywall: false,
  },
  {
    id: 269, title: "Civil Engineer", company: "Engro Corporation",
    companyUrl: "https://engrocorporation.com",
    location: "Rawalpindi, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 33.5651, lng: 73.0169,
    salary: "Rs250K - Rs350K/month",
    salaryMin: 250000, salaryMax: 350000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@engrocorporation.com",
    paywall: true,
  },
  {
    id: 270, title: "Remote Customer Support Specialist", company: "Habib Bank",
    companyUrl: "https://habibbank.com",
    location: "Faisalabad, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 31.4504, lng: 73.135,
    salary: "Rs275K - Rs375K/month",
    salaryMin: 275000, salaryMax: 375000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@habibbank.com",
    paywall: false,
  },
  {
    id: 271, title: "DevOps Engineer", company: "Lucky Cement",
    companyUrl: "https://luckycement.com",
    location: "Karachi, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 24.8607, lng: 67.0011,
    salary: "Rs300K - Rs400K/month",
    salaryMin: 300000, salaryMax: 400000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@luckycement.com",
    paywall: true,
  },
  {
    id: 272, title: "Business Development Manager", company: "PTCL",
    companyUrl: "https://ptcl.com",
    location: "Lahore, Pakistan", country: "pk", countryName: "Pakistan",
    lat: 31.5204, lng: 74.3587,
    salary: "Rs325K - Rs425K/month",
    salaryMin: 325000, salaryMax: 425000,
    salaryCurrency: "PKR", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@ptcl.com",
    paywall: false,
  },
  {
    id: 273, title: "Senior Software Engineer", company: "Grameenphone",
    companyUrl: "https://grameenphone.com",
    location: "Dhaka, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 23.8103, lng: 90.4125,
    salary: "৳15K - ৳36K/month",
    salaryMin: 15000, salaryMax: 36666,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@grameenphone.com",
    paywall: true,
  },
  {
    id: 274, title: "Data Analyst", company: "bKash",
    companyUrl: "https://bkash.com",
    location: "Chittagong, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 22.3569, lng: 91.7832,
    salary: "৳20K - ৳42K/month",
    salaryMin: 20416, salaryMax: 42082,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@bkash.com",
    paywall: false,
  },
  {
    id: 275, title: "Financial Accountant", company: "BRAC",
    companyUrl: "https://brac.com",
    location: "Sylhet, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 24.8949, lng: 91.8687,
    salary: "৳25K - ৳47K/month",
    salaryMin: 25833, salaryMax: 47499,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@brac.com",
    paywall: true,
  },
  {
    id: 276, title: "Marketing Manager", company: "Robi Axiata",
    companyUrl: "https://robiaxiata.com",
    location: "Rajshahi, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 24.3745, lng: 88.6042,
    salary: "৳31K - ৳52K/month",
    salaryMin: 31250, salaryMax: 52916,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@robiaxiata.com",
    paywall: false,
  },
  {
    id: 277, title: "UX/UI Designer", company: "Square Group",
    companyUrl: "https://squaregroup.com",
    location: "Khulna, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 22.8456, lng: 89.5403,
    salary: "৳36K - ৳58K/month",
    salaryMin: 36666, salaryMax: 58332,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@squaregroup.com",
    paywall: true,
  },
  {
    id: 278, title: "Sales Executive", company: "Pran-RFL",
    companyUrl: "https://pranrfl.com",
    location: "Dhaka, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 23.8103, lng: 90.4125,
    salary: "৳42K - ৳63K/month",
    salaryMin: 42083, salaryMax: 63749,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@pranrfl.com",
    paywall: false,
  },
  {
    id: 279, title: "Project Manager", company: "Beximco",
    companyUrl: "https://beximco.com",
    location: "Chittagong, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 22.3569, lng: 91.7832,
    salary: "৳47K - ৳69K/month",
    salaryMin: 47500, salaryMax: 69166,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@beximco.com",
    paywall: true,
  },
  {
    id: 280, title: "Registered Nurse", company: "Standard Chartered BD",
    companyUrl: "https://standardcharteredbd.com",
    location: "Sylhet, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 24.8949, lng: 91.8687,
    salary: "৳52K - ৳74K/month",
    salaryMin: 52916, salaryMax: 74582,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@standardcharteredbd.com",
    paywall: false,
  },
  {
    id: 281, title: "Civil Engineer", company: "Grameenphone",
    companyUrl: "https://grameenphone.com",
    location: "Rajshahi, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 24.3745, lng: 88.6042,
    salary: "৳58K - ৳79K/month",
    salaryMin: 58333, salaryMax: 79999,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@grameenphone.com",
    paywall: true,
  },
  {
    id: 282, title: "Remote Customer Support Specialist", company: "bKash",
    companyUrl: "https://bkash.com",
    location: "Khulna, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 22.8456, lng: 89.5403,
    salary: "৳63K - ৳85K/month",
    salaryMin: 63750, salaryMax: 85416,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@bkash.com",
    paywall: false,
  },
  {
    id: 283, title: "DevOps Engineer", company: "BRAC",
    companyUrl: "https://brac.com",
    location: "Dhaka, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 23.8103, lng: 90.4125,
    salary: "৳69K - ৳90K/month",
    salaryMin: 69166, salaryMax: 90832,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@brac.com",
    paywall: true,
  },
  {
    id: 284, title: "Business Development Manager", company: "Robi Axiata",
    companyUrl: "https://robiaxiata.com",
    location: "Chittagong, Bangladesh", country: "bd", countryName: "Bangladesh",
    lat: 22.3569, lng: 91.7832,
    salary: "৳74K - ৳96K/month",
    salaryMin: 74583, salaryMax: 96249,
    salaryCurrency: "BDT", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@robiaxiata.com",
    paywall: false,
  },
  {
    id: 285, title: "Senior Software Engineer", company: "Bancolombia",
    companyUrl: "https://bancolombia.com",
    location: "Bogota, Colombia", country: "co", countryName: "Colombia",
    lat: 4.711, lng: -74.0721,
    salary: "$2500K - $4M/month",
    salaryMin: 2500000, salaryMax: 4666666,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@bancolombia.com",
    paywall: true,
  },
  {
    id: 286, title: "Data Analyst", company: "Ecopetrol",
    companyUrl: "https://ecopetrol.com",
    location: "Medellin, Colombia", country: "co", countryName: "Colombia",
    lat: 6.2442, lng: -75.5812,
    salary: "$3041K - $5M/month",
    salaryMin: 3041666, salaryMax: 5208332,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@ecopetrol.com",
    paywall: false,
  },
  {
    id: 287, title: "Financial Accountant", company: "Grupo Aval",
    companyUrl: "https://grupoaval.com",
    location: "Cali, Colombia", country: "co", countryName: "Colombia",
    lat: 3.4516, lng: -76.532,
    salary: "$3583K - $5M/month",
    salaryMin: 3583333, salaryMax: 5749999,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@grupoaval.com",
    paywall: true,
  },
  {
    id: 288, title: "Marketing Manager", company: "Rappi",
    companyUrl: "https://rappi.com",
    location: "Barranquilla, Colombia", country: "co", countryName: "Colombia",
    lat: 10.9639, lng: -74.7813,
    salary: "$4125K - $6M/month",
    salaryMin: 4125000, salaryMax: 6291666,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@rappi.com",
    paywall: false,
  },
  {
    id: 289, title: "UX/UI Designer", company: "Davivienda",
    companyUrl: "https://davivienda.com",
    location: "Cartagena, Colombia", country: "co", countryName: "Colombia",
    lat: 10.391, lng: -75.5364,
    salary: "$4666K - $6M/month",
    salaryMin: 4666666, salaryMax: 6833332,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@davivienda.com",
    paywall: true,
  },
  {
    id: 290, title: "Sales Executive", company: "Carvajal",
    companyUrl: "https://carvajal.com",
    location: "Bogota, Colombia", country: "co", countryName: "Colombia",
    lat: 4.711, lng: -74.0721,
    salary: "$5208K - $7M/month",
    salaryMin: 5208333, salaryMax: 7374999,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@carvajal.com",
    paywall: false,
  },
  {
    id: 291, title: "Project Manager", company: "Grupo Sura",
    companyUrl: "https://gruposura.com",
    location: "Medellin, Colombia", country: "co", countryName: "Colombia",
    lat: 6.2442, lng: -75.5812,
    salary: "$5750K - $7M/month",
    salaryMin: 5750000, salaryMax: 7916666,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@gruposura.com",
    paywall: true,
  },
  {
    id: 292, title: "Registered Nurse", company: "Nutresa",
    companyUrl: "https://nutresa.com",
    location: "Cali, Colombia", country: "co", countryName: "Colombia",
    lat: 3.4516, lng: -76.532,
    salary: "$6291K - $8M/month",
    salaryMin: 6291666, salaryMax: 8458332,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@nutresa.com",
    paywall: false,
  },
  {
    id: 293, title: "Civil Engineer", company: "Bancolombia",
    companyUrl: "https://bancolombia.com",
    location: "Barranquilla, Colombia", country: "co", countryName: "Colombia",
    lat: 10.9639, lng: -74.7813,
    salary: "$6833K - $8M/month",
    salaryMin: 6833333, salaryMax: 8999999,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@bancolombia.com",
    paywall: true,
  },
  {
    id: 294, title: "Remote Customer Support Specialist", company: "Ecopetrol",
    companyUrl: "https://ecopetrol.com",
    location: "Cartagena, Colombia", country: "co", countryName: "Colombia",
    lat: 10.391, lng: -75.5364,
    salary: "$7375K - $9M/month",
    salaryMin: 7375000, salaryMax: 9541666,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@ecopetrol.com",
    paywall: false,
  },
  {
    id: 295, title: "DevOps Engineer", company: "Grupo Aval",
    companyUrl: "https://grupoaval.com",
    location: "Bogota, Colombia", country: "co", countryName: "Colombia",
    lat: 4.711, lng: -74.0721,
    salary: "$7916K - $10M/month",
    salaryMin: 7916666, salaryMax: 10083332,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@grupoaval.com",
    paywall: true,
  },
  {
    id: 296, title: "Business Development Manager", company: "Rappi",
    companyUrl: "https://rappi.com",
    location: "Medellin, Colombia", country: "co", countryName: "Colombia",
    lat: 6.2442, lng: -75.5812,
    salary: "$8458K - $10M/month",
    salaryMin: 8458333, salaryMax: 10624999,
    salaryCurrency: "COP", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@rappi.com",
    paywall: false,
  },
  {
    id: 297, title: "Senior Software Engineer", company: "OCP Group",
    companyUrl: "https://ocpgroup.com",
    location: "Casablanca, Morocco", country: "ma", countryName: "Morocco",
    lat: 33.5731, lng: -7.5898,
    salary: "MAD5K - MAD13K/month",
    salaryMin: 5000, salaryMax: 13333,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Design and develop scalable web applications using modern frameworks. Collaborate with cross-functional teams to deliver high-quality software solutions. Experience with cloud services and CI/CD pipelines required.", sector: "Technology",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@ocpgroup.com",
    paywall: true,
  },
  {
    id: 298, title: "Data Analyst", company: "Maroc Telecom",
    companyUrl: "https://maroctelecom.com",
    location: "Rabat, Morocco", country: "ma", countryName: "Morocco",
    lat: 34.0209, lng: -6.8416,
    salary: "MAD7K - MAD15K/month",
    salaryMin: 7083, salaryMax: 15416,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Analyze large datasets to extract actionable business insights. Create dashboards and reports using SQL, Python, and visualization tools. Support decision-making with data-driven recommendations.", sector: "Data Science",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@maroctelecom.com",
    paywall: false,
  },
  {
    id: 299, title: "Financial Accountant", company: "Attijariwafa Bank",
    companyUrl: "https://attijariwafabank.com",
    location: "Marrakech, Morocco", country: "ma", countryName: "Morocco",
    lat: 31.6295, lng: -7.9811,
    salary: "MAD9K - MAD17K/month",
    salaryMin: 9166, salaryMax: 17499,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Manage financial reporting, budgeting, and forecasting. Ensure compliance with local regulations and international accounting standards. Prepare monthly and annual financial statements.", sector: "Finance",
    posted: "1 day ago", type: "Full-time",
    contactEmail: "careers@attijariwafabank.com",
    paywall: true,
  },
  {
    id: 300, title: "Marketing Manager", company: "ONCF",
    companyUrl: "https://oncf.com",
    location: "Tangier, Morocco", country: "ma", countryName: "Morocco",
    lat: 35.7595, lng: -5.834,
    salary: "MAD11K - MAD19K/month",
    salaryMin: 11250, salaryMax: 19583,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Develop and execute marketing strategies across digital channels. Manage campaign budgets, analyze performance metrics, and optimize ROI. Lead a team of marketing specialists.", sector: "Marketing",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@oncf.com",
    paywall: false,
  },
  {
    id: 301, title: "UX/UI Designer", company: "RAM",
    companyUrl: "https://ram.com",
    location: "Fez, Morocco", country: "ma", countryName: "Morocco",
    lat: 34.0331, lng: -5.0003,
    salary: "MAD13K - MAD21K/month",
    salaryMin: 13333, salaryMax: 21666,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Create user-centered designs for web and mobile applications. Conduct user research, build wireframes and prototypes, and collaborate with developers to implement designs.", sector: "Design",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@ram.com",
    paywall: true,
  },
  {
    id: 302, title: "Sales Executive", company: "Managem",
    companyUrl: "https://managem.com",
    location: "Casablanca, Morocco", country: "ma", countryName: "Morocco",
    lat: 33.5731, lng: -7.5898,
    salary: "MAD15K - MAD23K/month",
    salaryMin: 15416, salaryMax: 23749,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Drive revenue growth by identifying and pursuing new business opportunities. Build and maintain client relationships, negotiate contracts, and exceed sales targets consistently.", sector: "Sales",
    posted: "5 days ago", type: "Full-time",
    contactEmail: "careers@managem.com",
    paywall: false,
  },
  {
    id: 303, title: "Project Manager", company: "Inwi",
    companyUrl: "https://inwi.com",
    location: "Rabat, Morocco", country: "ma", countryName: "Morocco",
    lat: 34.0209, lng: -6.8416,
    salary: "MAD17K - MAD25K/month",
    salaryMin: 17500, salaryMax: 25833,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Oversee project planning, execution, and delivery within scope and budget. Coordinate with stakeholders, manage risks, and ensure timely completion of milestones.", sector: "Management",
    posted: "1 week ago", type: "Full-time",
    contactEmail: "careers@inwi.com",
    paywall: true,
  },
  {
    id: 304, title: "Registered Nurse", company: "Tanger Med",
    companyUrl: "https://tangermed.com",
    location: "Marrakech, Morocco", country: "ma", countryName: "Morocco",
    lat: 31.6295, lng: -7.9811,
    salary: "MAD19K - MAD27K/month",
    salaryMin: 19583, salaryMax: 27916,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Provide patient care in clinical settings, administer medications, and monitor patient progress. Collaborate with healthcare teams to develop treatment plans and maintain accurate records.", sector: "Healthcare",
    posted: "2 hours ago", type: "Full-time",
    contactEmail: "careers@tangermed.com",
    paywall: false,
  },
  {
    id: 305, title: "Civil Engineer", company: "OCP Group",
    companyUrl: "https://ocpgroup.com",
    location: "Tangier, Morocco", country: "ma", countryName: "Morocco",
    lat: 35.7595, lng: -5.834,
    salary: "MAD21K - MAD29K/month",
    salaryMin: 21666, salaryMax: 29999,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Plan, design, and oversee construction of infrastructure projects. Conduct site assessments, prepare technical drawings, and ensure compliance with safety and building regulations.", sector: "Engineering",
    posted: "5 hours ago", type: "Full-time",
    contactEmail: "careers@ocpgroup.com",
    paywall: true,
  },
  {
    id: 306, title: "Remote Customer Support Specialist", company: "Maroc Telecom",
    companyUrl: "https://maroctelecom.com",
    location: "Fez, Morocco", country: "ma", countryName: "Morocco",
    lat: 34.0331, lng: -5.0003,
    salary: "MAD23K - MAD32K/month",
    salaryMin: 23750, salaryMax: 32083,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Handle customer inquiries via phone, email, and chat. Troubleshoot technical issues, escalate complex cases, and maintain high customer satisfaction scores.", sector: "Technology",
    posted: "1 day ago", type: "Remote",
    contactEmail: "careers@maroctelecom.com",
    paywall: false,
  },
  {
    id: 307, title: "DevOps Engineer", company: "Attijariwafa Bank",
    companyUrl: "https://attijariwafabank.com",
    location: "Casablanca, Morocco", country: "ma", countryName: "Morocco",
    lat: 33.5731, lng: -7.5898,
    salary: "MAD25K - MAD34K/month",
    salaryMin: 25833, salaryMax: 34166,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Build and maintain CI/CD pipelines, manage cloud infrastructure, and automate deployment processes. Monitor system performance and ensure high availability.", sector: "Technology",
    posted: "2 days ago", type: "Full-time",
    contactEmail: "careers@attijariwafabank.com",
    paywall: true,
  },
  {
    id: 308, title: "Business Development Manager", company: "ONCF",
    companyUrl: "https://oncf.com",
    location: "Rabat, Morocco", country: "ma", countryName: "Morocco",
    lat: 34.0209, lng: -6.8416,
    salary: "MAD27K - MAD36K/month",
    salaryMin: 27916, salaryMax: 36249,
    salaryCurrency: "MAD", salaryPeriod: "month",
    description: "Identify growth opportunities and strategic partnerships. Develop business plans, negotiate deals, and expand market presence in the region.", sector: "Management",
    posted: "3 days ago", type: "Full-time",
    contactEmail: "careers@oncf.com",
    paywall: false,
  },
];

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const country = searchParams.get("country");
  let filtered = jobs;
  if (country) {
    filtered = jobs.filter(j => j.country === country);
  }
  return NextResponse.json(filtered);
}